'use strict';
// scripts/himmelctl/lib/launcher.js — PATH launcher marker/write/remove
// primitives extracted out of bin.js (HIMMEL-3312 S13 item 1). Pure refactor:
// same implementations, same call sites (bin.js's applyHimmelctlPathShim and
// removeHimmelctlLaunchers), same seam env vars (HIMMELCTL_BIN_DIR) — bin.js
// now `require`s these instead of defining them inline. Also required by the
// new lib/standalone-bundle.js closure list (S13 item 3).

const fs = require('fs');
const path = require('path');
const os = require('os');
const provLib = require('./provenance.js');

function provWarn(e) {
  console.error(`himmelctl: WARN: provenance ledger not updated (${e && e.message ? e.message : e})`);
}

// One artifact row: prov(['create', 'file', path, ...flags]). Prints the DRY:
// line a --dry-run flag yields. Duplicated from bin.js's own prov() (same
// body) so this module has no dependency back on bin.js.
function prov(recArgs) {
  try {
    const dry = provLib.provRecord(recArgs);
    if (dry) console.log(dry);
  } catch (e) { provWarn(e); }
}

// Snapshot a file's pre-write state; call the returned function AFTER the
// write to record it (create when it was absent, replace when not).
function provBefore(p, spec) {
  let pre;
  try {
    pre = fs.existsSync(p)
      ? { op: 'replace', flags: ['--pre-text', fs.readFileSync(p, 'utf8'), ...(spec.cls === 'keep' ? [] : ['--backup'])] }
      : { op: 'create', flags: ['--pre-absent'] };
  } catch (e) {
    provWarn(e);
    return () => {};
  }
  return () => prov([pre.op, spec.kind || 'file', p, ...pre.flags, '--post-file', p,
    '--scope', spec.scope, '--class', spec.cls, ...(spec.row ? ['--row', spec.row] : [])]);
}

// setup.sh already treats ~/.local/bin as himmel's shared user-bin directory
// (uv, jira, pre-commit). Reuse it rather than inventing another PATH surface.
// HIMMELCTL_BIN_DIR is a hermetic-test seam; normal runs always use ~/.local/bin.
function himmelctlBinDir() {
  if (process.env.HIMMELCTL_BIN_DIR) return path.resolve(process.env.HIMMELCTL_BIN_DIR);
  return path.join(process.platform === 'win32' ? os.homedir() : (process.env.HOME || os.homedir()), '.local', 'bin');
}

// HIMMEL-1446 r2 (codex adversarial review, 3 agreed blockers):
//  • The loader target is the PRIMARY checkout, not repoRoot() — a launcher
//    written from a linked feature worktree must not bind to the disposable
//    worktree.
//  • Every generated file carries SHIM_MARKER; an existing destination is
//    overwritten ONLY if it already carries the marker (writeMarkedLauncher).
//    A third-party `himmelctl`, an operator's hand-written launcher, or a
//    symlink is refused, never clobbered. Writes go via a sibling tmp + atomic
//    rename so a partial write can never leave a broken launcher.
//  • No himmelctl.ps1 is written: PowerShell command precedence resolves a .ps1
//    before the .cmd of the same basename, and a clean Windows client defaults
//    to ExecutionPolicy=Restricted → bare `himmelctl` throws PSSecurityException.
//    Letting PowerShell resolve the .cmd avoids that. A stale marked .ps1 from a
//    prior install is removed (removeMarkedLauncher).
const SHIM_MARKER = 'generated by himmelctl (HIMMEL-1446)';

// True iff <filePath> exists and its contents carry our ownership marker. An
// absent file is "not marked" (ENOENT -> false); any other read error throws.
function fileCarriesMarker(filePath) {
  let content;
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch (e) {
    if (e && e.code === 'ENOENT') return false;
    throw e;
  }
  return content.includes(SHIM_MARKER);
}

// Write <contents> to <dest> (optional <mode> for chmod), but ONLY when dest is
// absent OR already carries our ownership marker. A third-party file, an
// operator's hand-written launcher, or a symlink (lstat, never followed) is
// refused with a clear message — never clobbered. Writes go via a sibling tmp +
// atomic rename, so a crash mid-write or a failed write can never leave a
// partial launcher at dest (the orphaned tmp is a hidden dotfile). Returns true
// on success, false on a refused collision. Throws on I/O error. (codex-adv-3.)
function writeMarkedLauncher(dest, contents, mode) {
  // Existence is probed with lstatSync, NOT fs.existsSync (HIMMEL-1446 r4 glm-2):
  // existsSync FOLLOWS symlinks, so a BROKEN (dangling) symlink at dest returns
  // false, skipping the symlink/ownership check and letting renameSync clobber
  // the link — violating the never-clobber-a-symlink contract. lstatSync never
  // follows, so ANY symlink (broken included) reaches the isSymbolicLink()
  // refusal. ENOENT (truly absent) is the only skip-to-write case.
  let st = null;
  try {
    st = fs.lstatSync(dest);
  } catch (e) {
    if (e && e.code !== 'ENOENT') throw e; // ENOENT -> st stays null: absent, safe to write
  }
  if (st) {
    if (st.isSymbolicLink()) {
      console.error(`himmelctl: refusing to overwrite symlink ${dest} (remove it first if you want himmelctl to manage it)`);
      return false;
    }
    if (!fileCarriesMarker(dest)) {
      console.error(`himmelctl: refusing to overwrite ${dest} (not a himmelctl-managed file — move it aside first)`);
      return false;
    }
  }
  const tmp = path.join(path.dirname(dest), `.${path.basename(dest)}.${process.pid}.tmp`);
  const recorded = provBefore(dest, { kind: 'shim', scope: 'user', cls: 'code' });
  try {
    fs.writeFileSync(tmp, contents, 'utf8');
    if (mode !== undefined) fs.chmodSync(tmp, mode);
    fs.renameSync(tmp, dest);
    recorded();
  } catch (e) {
    try { fs.unlinkSync(tmp); } catch (_e) { /* best-effort tmp cleanup */ }
    throw e;
  }
  return true;
}

// Remove <filePath> only if it carries our ownership marker; an unmarked file
// (a third-party `himmelctl`) or a symlink is left untouched. Absent file is a
// no-op. Used by the shim (stale .ps1 cleanup) and cmdUninstall.
function removeMarkedLauncher(filePath) {
  let st;
  try {
    st = fs.lstatSync(filePath);
  } catch (e) {
    if (e && e.code === 'ENOENT') return;
    throw e;
  }
  if (st.isSymbolicLink()) return; // never follow/remove an unowned symlink
  if (!fileCarriesMarker(filePath)) return; // never remove an unmarked file
  fs.unlinkSync(filePath);
}

// HIMMEL-1446 r2 (glm-1): uninstall.sh/.ps1 tears down himmel's machine wiring
// but does not know about the PATH launchers install/update wrote into binDir
// (~/.local/bin), so they'd go stale (dangling once the clone is deleted).
// Remove each known launcher name that carries our ownership marker; never
// touch an unmarked or symlinked file. Best-effort: WARNs on errors and never
// changes the caller's exit code.
function removeHimmelctlLaunchers() {
  const binDir = himmelctlBinDir();
  for (const name of ['himmelctl.js', 'himmelctl', 'himmelctl.cmd', 'himmelctl.ps1']) {
    try {
      removeMarkedLauncher(path.join(binDir, name));
    } catch (e) {
      console.error(`himmelctl: WARN: could not remove launcher ${path.join(binDir, name)} (${e.message}) — skipping`);
    }
  }
}

module.exports = {
  SHIM_MARKER,
  himmelctlBinDir,
  fileCarriesMarker,
  writeMarkedLauncher,
  removeMarkedLauncher,
  removeHimmelctlLaunchers,
};
