#!/usr/bin/env bash
# End-to-end verification of handover-v2 against the current state.
#
# Usage: bash marketplace/plugins/handover/scripts/test-skill-e2e.sh
#
# Exit codes:
#   0 — all checks pass
#   1 — at least one check failed
set -uo pipefail
SLUG="hbtest$$"   # generated neutral test user-slug (not hardcoded)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
MIGRATE="$SCRIPT_DIR/migrate-v1-to-v2.sh"

pass=0
fail=0
note() { echo "[$1] $2"; }
ok() { pass=$((pass+1)); note OK "$1"; }
ko() { fail=$((fail+1)); note FAIL "$1"; }

# 1. Migration script executable
if [ -x "$MIGRATE" ]; then ok "migrate script executable"; else ko "migrate script not executable"; fi

# 2. Migration smoke test passes
if bash "$SCRIPT_DIR/test-migrate-v1-to-v2.sh" >/dev/null 2>&1; then
  ok "migrate smoke test"
else
  ko "migrate smoke test failed"
fi

# 3. (Jira CLI build + tests removed, HIMMEL-3196.) They need scripts/jira's own
# node_modules — not this suite's business — and CI's node-suites matrix already
# runs `npm ci && npm test` for scripts/jira.

# 4. Every template is v2-tagged
v1_count=$(grep -lE '^template_version: 1' \
              "$ROOT/marketplace/plugins/handover/templates/"*.md 2>/dev/null \
           | wc -l)
if [ "$v1_count" -eq 0 ]; then ok "no v1 templates remain"; else ko "$v1_count v1 templates remain"; fi

# 5. SKILL.md references all v2 reference files
SKILL="$ROOT/marketplace/plugins/handover/skills/handover/SKILL.md"
refs=(v2-schema buckets sync hygiene routing init-register)
missing=0
for r in "${refs[@]}"; do
  grep -q "references/$r.md" "$SKILL" || { missing=$((missing+1)); echo "  miss: references/$r.md"; }
done
if [ "$missing" -eq 0 ]; then ok "SKILL.md references all v2 docs"; else ko "$missing references missing from SKILL.md"; fi

# 6-8. Migrate a fixture state root and assert what migrate-v1-to-v2.sh really
# writes (HIMMEL-3196). This used to assert against $ROOT/handovers/$SLUG, a
# per-PID slug under himmel's stub handovers/ that nothing ever created, so the
# presence checks were always red and the absence checks always vacuously green.
# status.md / roadmap.md / tech-debt.md are NOT asserted: they are generated by
# the LLM-driven `update-status` flow (references/update-status.md), not by a
# script, so a shell suite has nothing to run to produce them.
FIX="$(mktemp -d "${TMPDIR:-/tmp}/skill-e2e.XXXXXX")" || { echo "FAIL: mktemp"; exit 1; }
trap 'rm -rf "$FIX"' EXIT
STATE="$FIX/handovers/$SLUG"
ITEM="$STATE/epics/#15-rename-himmel-and-jira"
mkdir -p "$ITEM/tasks"
printf -- '---\ntemplate_version: 1\n---\n# #15 — rename-himmel-and-jira\n\n**Status:** done\n**Jira:** HIMMEL-15\n' > "$ITEM/master-plan.md"
printf '# Counter\nNext: 16\n' > "$STATE/counter.md"
"$MIGRATE" --root "$FIX" --no-jira-create --quiet >/dev/null 2>&1 || true

# 6. Post-migration: the keyed item was renamed and no #N dirs remain
nstale=$(find "$STATE" -type d -name '#*' 2>/dev/null | wc -l)
if [ "$nstale" -eq 0 ] && [ -d "$STATE/epics/HIMMEL-15-rename-himmel-and-jira" ]; then
  ok "no #N dirs after migration, keyed item renamed"
else
  ko "migration left $nstale #N dirs or did not rename the keyed item"
fi

# 7. counter.md survives migration
if [ -f "$STATE/counter.md" ]; then ok "counter.md preserved"; else ko "counter.md missing after migration"; fi

# 8. Every migrated item has v2 frontmatter (template_version: 2)
v1_items=$(find "$STATE" -type f -name '*.md' -exec grep -lE '^template_version: 1$' {} \; 2>/dev/null | wc -l)
if [ "$v1_items" -eq 0 ] \
   && grep -qE '^template_version: 2$' "$STATE/epics/HIMMEL-15-rename-himmel-and-jira/master-plan.md" 2>/dev/null; then
  ok "migrated item carries v2 frontmatter"
else
  ko "$v1_items items still v1, or the migrated item is not v2"
fi

# 9. Every next-session template declares resume_cwd: frontmatter (HIMMEL-2147) --
# arm-resume.sh reads this key to resolve which repo an unattended resume runs
# in; a template missing it is the source of the auto-detect-into-single-writer
# failure mode item 1b's registry fallback exists to catch.
missing_rc=0
for t in "$ROOT/marketplace/plugins/handover/templates/"*-next-session.md; do
  [ -f "$t" ] || continue
  # key must sit inside the FIRST frontmatter block with a non-empty value —
  # a body-text match or an empty value would still hit the runtime fallback.
  # Capture first, then grep a here-string (not a pipe): under `set -o
  # pipefail`, grep -q exits on first match and can SIGPIPE a producer on the
  # other end of any pipe, turning a genuine match into a non-zero pipeline
  # (HIMMEL-1430 grep-q-pipe-under-pipefail class). Frontmatter is tiny, well
  # under the 64KiB here-string limit.
  fm=$(awk '/^---$/{n++;next} n==1' "$t")
  grep -qE '^resume_cwd:[[:space:]]*[^[:space:]]' <<< "$fm" \
    || { missing_rc=$((missing_rc+1)); echo "  miss: non-empty resume_cwd: in frontmatter of $t"; }
done
if [ "$missing_rc" -eq 0 ]; then ok "all next-session templates declare resume_cwd:"; else ko "$missing_rc next-session templates missing resume_cwd:"; fi

# 10. Task legs carry the one canonical handover threshold policy
# (HIMMEL-2779): fill OR per-turn input tokens, whichever arrives first.
TASK_NEXT="$ROOT/marketplace/plugins/handover/templates/task-next-session.md"
if grep -qF '45% context fill OR 90,000 input tokens this turn, whichever comes first' "$TASK_NEXT" \
   && grep -qF 'scripts/context-fill.sh --warn-at 45' "$TASK_NEXT" \
   && grep -qF 'scripts/context-fill.sh --warn-at 90000' "$TASK_NEXT"; then
  ok "task-next-session template carries the 45%/90,000 leg handover policy"
else
  ko "task-next-session template is missing the 45%/90,000 leg handover policy"
fi

echo "Total: pass=$pass fail=$fail"
[ "$fail" -eq 0 ]
