#!/usr/bin/env bash
# Tests for HIMMEL-660 follow-list-score.mjs — Task 7 `assemble` subcommand.
# Reads <handle>.judgment.json + dossier JSON fixtures written directly to
# disk (no live judge pass), ranks via follow-score.mjs's rankAccounts
# against the real ./follow-overrides.json seed ({whitelist:["examplehandle"],
# exclude:[]}), and asserts the regenerated ai-x-follow-list.md +
# ai-x-follow-scores.md. Hermetic: no network. Cross-platform: bash on
# Linux/macOS/Git-Bash. Uses node (not bun) for CI.

set -u -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$(cd "$SCRIPT_DIR/../tools" && pwd)"
CLI="$TOOLS_DIR/follow-list-score.mjs"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

pass=0
fail=0
assert() {
    local desc="$1" expected="$2" actual="$3"
    if [ "$expected" = "$actual" ]; then
        echo "  PASS  $desc"; pass=$((pass+1))
    else
        echo "  FAIL  $desc"; echo "         expected: $expected"; echo "         actual:   $actual"; fail=$((fail+1))
    fi
}

node --check "$CLI" 2>/dev/null && s=ok || s=fail
assert "follow-list-score.mjs parses" ok "$s"

# -- fixture vault: existing list file (frontmatter + stale Tier 1 + footer) -
vault="$tmpdir/vault"
mkdir -p "$vault/.obsidian" "$vault/30-Resources/.follow-scores"

list_path="$vault/30-Resources/ai-x-follow-list.md"
scorecard_path="$vault/30-Resources/ai-x-follow-scores.md"

cat > "$list_path" <<'EOF'
---
title: "AI X Follow List"
updated: 2026-06-01
---

## Tier 1 — core

- **[@old](https://x.com/old)** (10) — stale entry, should be replaced by assemble

> **correction:** operator override note that must survive assemble byte-identical.

---
**Why this list exists:** this list curates X/Twitter accounts worth following for
agent-harness, orchestration, and second-brain signal. Regenerated by
`follow-list-score.mjs assemble` from judge-scored dossiers; do not
hand-edit the tier sections above this line.

Related: [[SomeMOC]]
EOF

cp "$list_path" "$tmpdir/original-list.md"

# -- dossier + judgment fixtures ---------------------------------------------
# alice: Tier 1 (composite 4.0, confidence high -> adjusted 4.0), >=1 verified claim.
cat > "$vault/30-Resources/.follow-scores/alice.json" <<'EOF'
{
  "handle": "alice",
  "roster": { "clip_count": 5, "in_list": true },
  "account": { "bio": "building agent harnesses", "followers": 5000, "following": 10, "created_at": null, "cadence_days": 3, "source": "fxtwitter", "fetch_status": "ok" },
  "repos": { "login": "alice", "repo_count": 4, "total_stars": 120, "recent_pushed_at": null, "topical_hits": 2, "sample_descriptions": ["an agent harness"], "source": "github", "status": "ok" },
  "corpus": { "sample_tweets": [{ "text": "shipped a new orchestration tool", "stats": null }], "crypto_tagged": false },
  "claims": [
    { "text": "github.com/alice/harness", "kind": "repo", "status": "verified" },
    { "text": "5000 followers", "kind": "followers", "status": "verified" }
  ],
  "injection_suspect": false,
  "screen_status": "ok"
}
EOF
cat > "$vault/30-Resources/.follow-scores/alice.judgment.json" <<'EOF'
{
  "handle": "alice",
  "scores": { "factual_reliability": 4, "resources": 4, "focus_fit": 4, "substance": 4, "reach": 4 },
  "confidence": "high",
  "rationale": "strong agent-harness builder with verified repo evidence",
  "grounding_notes": "verified repo + followers claims"
}
EOF

# bob: Tier 2 (composite 3.0, confidence high -> adjusted 3.0), >=1 verified claim.
cat > "$vault/30-Resources/.follow-scores/bob.json" <<'EOF'
{
  "handle": "bob",
  "roster": { "clip_count": 6, "in_list": true },
  "account": { "bio": "second-brain tinkerer", "followers": 800, "following": 50, "created_at": null, "cadence_days": 5, "source": "fxtwitter", "fetch_status": "ok" },
  "repos": { "login": "bob", "repo_count": 1, "total_stars": 3, "recent_pushed_at": null, "topical_hits": 0, "sample_descriptions": [], "source": "github", "status": "ok" },
  "corpus": { "sample_tweets": [{ "text": "notes on context engineering", "stats": null }], "crypto_tagged": false },
  "claims": [
    { "text": "github.com/bob/notes", "kind": "repo", "status": "verified" }
  ],
  "injection_suspect": false,
  "screen_status": "ok"
}
EOF
cat > "$vault/30-Resources/.follow-scores/bob.judgment.json" <<'EOF'
{
  "handle": "bob",
  "scores": { "factual_reliability": 3, "resources": 3, "focus_fit": 3, "substance": 3, "reach": 3 },
  "confidence": "high",
  "rationale": "solid contributor, decent focus fit",
  "grounding_notes": "one verified repo claim"
}
EOF

# theo: Tier 3 (composite 2.0, confidence high -> adjusted 2.0), roster.clip_count==0
# (the low_sample case) but >=1 verified claim so the invariant holds via evidence.
cat > "$vault/30-Resources/.follow-scores/theo.json" <<'EOF'
{
  "handle": "theo",
  "roster": { "clip_count": 0, "in_list": true },
  "account": { "bio": "occasional poster", "followers": 200, "following": 100, "created_at": null, "cadence_days": null, "source": "fxtwitter", "fetch_status": "ok" },
  "repos": { "login": "theo", "repo_count": 1, "total_stars": 0, "recent_pushed_at": null, "topical_hits": 0, "sample_descriptions": [], "source": "github", "status": "ok" },
  "corpus": { "sample_tweets": [], "crypto_tagged": false },
  "claims": [
    { "text": "github.com/theo/tool", "kind": "repo", "status": "verified" }
  ],
  "injection_suspect": false,
  "screen_status": "ok"
}
EOF
cat > "$vault/30-Resources/.follow-scores/theo.judgment.json" <<'EOF'
{
  "handle": "theo",
  "scores": { "factual_reliability": 2, "resources": 2, "focus_fit": 2, "substance": 2, "reach": 2 },
  "confidence": "high",
  "rationale": "moderate signal, thin corpus in the vault so far",
  "grounding_notes": "one verified repo claim; sparse corpus"
}
EOF

# examplehandle: computes "exclude" (composite 1.0, confidence low -> adjusted 0.7),
# NO verified claims -- confidence:low satisfies the invariant instead.
# Whitelisted via the real ./follow-overrides.json seed -> must surface at Tier 3.
cat > "$vault/30-Resources/.follow-scores/examplehandle.json" <<'EOF'
{
  "handle": "examplehandle",
  "roster": { "clip_count": 3, "in_list": true },
  "account": { "bio": "quiet account", "followers": 50, "following": 20, "created_at": null, "cadence_days": null, "source": "fxtwitter", "fetch_status": "ok" },
  "repos": { "login": null, "repo_count": null, "total_stars": null, "recent_pushed_at": null, "topical_hits": null, "sample_descriptions": [], "source": null, "status": null },
  "corpus": { "sample_tweets": [], "crypto_tagged": false },
  "claims": [],
  "injection_suspect": false,
  "screen_status": "ok"
}
EOF
cat > "$vault/30-Resources/.follow-scores/examplehandle.judgment.json" <<'EOF'
{
  "handle": "examplehandle",
  "scores": { "factual_reliability": 1, "resources": 1, "focus_fit": 1, "substance": 1, "reach": 1 },
  "confidence": "low",
  "rationale": "borderline account, thin evidence",
  "grounding_notes": "no verifiable claims in the dossier"
}
EOF

# dave: computes "exclude" (composite 0.0), NOT whitelisted -> stays in ## Excluded.
cat > "$vault/30-Resources/.follow-scores/dave.json" <<'EOF'
{
  "handle": "dave",
  "roster": { "clip_count": 1, "in_list": false },
  "account": { "bio": "spam-adjacent bio", "followers": 10, "following": 5000, "created_at": null, "cadence_days": null, "source": "fxtwitter", "fetch_status": "ok" },
  "repos": { "login": null, "repo_count": null, "total_stars": null, "recent_pushed_at": null, "topical_hits": null, "sample_descriptions": [], "source": null, "status": null },
  "corpus": { "sample_tweets": [], "crypto_tagged": false },
  "claims": [],
  "injection_suspect": false,
  "screen_status": "ok"
}
EOF
cat > "$vault/30-Resources/.follow-scores/dave.judgment.json" <<'EOF'
{
  "handle": "dave",
  "scores": { "factual_reliability": 0, "resources": 0, "focus_fit": 0, "substance": 0, "reach": 0 },
  "confidence": "med",
  "rationale": "no usable signal",
  "grounding_notes": "n/a"
}
EOF

# -- Test 1: assemble runs, rewrites the list + writes the scorecard --------
echo "Test 1: assemble writes list + scorecard"

node "$CLI" assemble --vault "$vault" >/dev/null 2>&1
r1=$?
assert "assemble exits 0" 0 "$r1"

[ -f "$list_path" ] && le=exists || le=absent
assert "ai-x-follow-list.md still exists" exists "$le"
[ -f "$scorecard_path" ] && se=exists || se=absent
assert "ai-x-follow-scores.md written" exists "$se"

# -- Test 2: list content -- tier placement, whitelist override, stale entry gone
echo "Test 2: list content"

ORIG_LIST="$tmpdir/original-list.md" NEW_LIST="$list_path" node -e '
const fs = require("fs");
const orig = fs.readFileSync(process.env.ORIG_LIST, "utf8");
const updated = fs.readFileSync(process.env.NEW_LIST, "utf8");

function frontmatterBlock(text) {
  const lines = text.split("\n");
  if (lines[0] !== "---") return null;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === "---") return lines.slice(0, i + 1).join("\n");
  }
  return null;
}
function footerBlock(text) {
  const idx = text.indexOf("> **correction:**");
  return idx === -1 ? null : text.slice(idx);
}

console.log("FM_MATCH=" + (frontmatterBlock(orig) === frontmatterBlock(updated)));
console.log("FOOTER_MATCH=" + (footerBlock(orig) === footerBlock(updated)));
console.log("BLOCKQUOTE_PRESENT=" + updated.includes("> **correction:** operator override note that must survive assemble byte-identical."));
console.log("DASHES_PRESENT=" + /\n---\n/.test(updated));
console.log("FOOTER_PROSE_PRESENT=" + updated.includes("**Why this list exists:** this list curates X/Twitter accounts"));
console.log("RELATED_PRESENT=" + updated.includes("Related: [[SomeMOC]]"));
console.log("OLD_GONE=" + !updated.includes("@old"));
console.log("HAS_ALICE=" + updated.includes("[@alice]"));
console.log("HAS_BOB=" + updated.includes("[@bob]"));
console.log("HAS_THEO=" + updated.includes("[@theo]"));
console.log("HAS_CYRIL=" + updated.includes("[@examplehandle]"));
console.log("HAS_DAVE=" + updated.includes("[@dave]"));

const tier3Idx = updated.indexOf("## Tier 3");
const excludedIdx = updated.indexOf("## Excluded");
const cyrilIdx = updated.indexOf("[@examplehandle]");
console.log("CYRIL_IN_TIER3=" + (tier3Idx !== -1 && excludedIdx !== -1 && cyrilIdx > tier3Idx && cyrilIdx < excludedIdx));
const cyrilLine = updated.split("\n").find(l => l.includes("[@examplehandle]"));
console.log("CYRIL_HAS_OVERRIDE=" + (!!cyrilLine && /override/i.test(cyrilLine)));

const daveIdx = updated.indexOf("[@dave]");
console.log("DAVE_IN_EXCLUDED=" + (excludedIdx !== -1 && daveIdx > excludedIdx));
' > "$tmpdir/list-check.txt"

list_check="$(cat "$tmpdir/list-check.txt")"
echo "$list_check" | grep -q 'FM_MATCH=true' && r=yes || r=no; assert "frontmatter preserved byte-identical" yes "$r"
echo "$list_check" | grep -q 'FOOTER_MATCH=true' && r=yes || r=no; assert "blockquote+---+footer+Related tail preserved byte-identical" yes "$r"
echo "$list_check" | grep -q 'BLOCKQUOTE_PRESENT=true' && r=yes || r=no; assert "operator correction blockquote survives" yes "$r"
echo "$list_check" | grep -q 'DASHES_PRESENT=true' && r=yes || r=no; assert "bare --- separator survives" yes "$r"
echo "$list_check" | grep -q 'FOOTER_PROSE_PRESENT=true' && r=yes || r=no; assert "'Why this list exists' footer prose survives" yes "$r"
echo "$list_check" | grep -q 'RELATED_PRESENT=true' && r=yes || r=no; assert "Related: line survives" yes "$r"
echo "$list_check" | grep -q 'OLD_GONE=true' && r=yes || r=no; assert "stale tier-section entry replaced" yes "$r"
echo "$list_check" | grep -q 'HAS_ALICE=true' && r=yes || r=no; assert "alice present in list" yes "$r"
echo "$list_check" | grep -q 'HAS_BOB=true' && r=yes || r=no; assert "bob present in list" yes "$r"
echo "$list_check" | grep -q 'HAS_THEO=true' && r=yes || r=no; assert "theo present in list" yes "$r"
echo "$list_check" | grep -q 'HAS_CYRIL=true' && r=yes || r=no; assert "examplehandle present in list (whitelist override)" yes "$r"
echo "$list_check" | grep -q 'HAS_DAVE=true' && r=yes || r=no; assert "dave present in list (Excluded section)" yes "$r"
echo "$list_check" | grep -q 'CYRIL_IN_TIER3=true' && r=yes || r=no; assert "examplehandle placed at Tier 3, not promoted higher" yes "$r"
echo "$list_check" | grep -q 'CYRIL_HAS_OVERRIDE=true' && r=yes || r=no; assert "examplehandle's bullet carries an override note" yes "$r"
echo "$list_check" | grep -q 'DAVE_IN_EXCLUDED=true' && r=yes || r=no; assert "dave (computed exclude, not whitelisted) lands in ## Excluded" yes "$r"

# -- Test 3: scorecard content -- low_sample flag + verified-vs-confidence invariant
echo "Test 3: scorecard content"

SCORECARD="$scorecard_path" node -e '
const fs = require("fs");
const scorecard = fs.readFileSync(process.env.SCORECARD, "utf8");
function blockFor(handle) {
  const marker = "### @" + handle;
  const idx = scorecard.indexOf(marker);
  if (idx === -1) return "";
  const next = scorecard.indexOf("\n### @", idx + 1);
  return scorecard.slice(idx, next === -1 ? scorecard.length : next);
}
console.log("THEO_LOW_SAMPLE=" + /low_sample/.test(blockFor("theo")));
console.log("ALICE_VERIFIED=" + /verified: "/.test(blockFor("alice")));
console.log("BOB_VERIFIED=" + /verified: "/.test(blockFor("bob")));
console.log("THEO_VERIFIED=" + /verified: "/.test(blockFor("theo")));
console.log("CYRIL_CONF_LOW=" + /confidence: low/.test(blockFor("examplehandle")));
console.log("ALICE_BLOCK_NONEMPTY=" + (blockFor("alice").length > 0));
console.log("BOB_BLOCK_NONEMPTY=" + (blockFor("bob").length > 0));
console.log("THEO_BLOCK_NONEMPTY=" + (blockFor("theo").length > 0));
console.log("CYRIL_BLOCK_NONEMPTY=" + (blockFor("examplehandle").length > 0));
' > "$tmpdir/scorecard-check.txt"

scorecard_check="$(cat "$tmpdir/scorecard-check.txt")"
echo "$scorecard_check" | grep -q 'ALICE_BLOCK_NONEMPTY=true' && r=yes || r=no; assert "scorecard has an alice row" yes "$r"
echo "$scorecard_check" | grep -q 'BOB_BLOCK_NONEMPTY=true' && r=yes || r=no; assert "scorecard has a bob row" yes "$r"
echo "$scorecard_check" | grep -q 'THEO_BLOCK_NONEMPTY=true' && r=yes || r=no; assert "scorecard has a theo row" yes "$r"
echo "$scorecard_check" | grep -q 'CYRIL_BLOCK_NONEMPTY=true' && r=yes || r=no; assert "scorecard has a examplehandle row" yes "$r"
echo "$scorecard_check" | grep -q 'THEO_LOW_SAMPLE=true' && r=yes || r=no; assert "theo's row (roster.clip_count==0) is flagged low_sample" yes "$r"
echo "$scorecard_check" | grep -q 'ALICE_VERIFIED=true' && r=yes || r=no; assert "alice's row cites >=1 verified evidence item" yes "$r"
echo "$scorecard_check" | grep -q 'BOB_VERIFIED=true' && r=yes || r=no; assert "bob's row cites >=1 verified evidence item" yes "$r"
echo "$scorecard_check" | grep -q 'THEO_VERIFIED=true' && r=yes || r=no; assert "theo's row cites >=1 verified evidence item" yes "$r"
echo "$scorecard_check" | grep -q 'CYRIL_CONF_LOW=true' && r=yes || r=no; assert "examplehandle's row carries confidence: low (no verified evidence needed)" yes "$r"

# -- Test 4: determinism -- re-running assemble yields a byte-identical list -
echo "Test 4: determinism (re-run -> byte-identical)"

sha_before="$(node -e 'const c=require("fs").readFileSync(process.argv[1]);console.log(require("crypto").createHash("sha256").update(c).digest("hex"))' "$list_path")"

node "$CLI" assemble --vault "$vault" >/dev/null 2>&1
r2=$?
assert "second assemble run exits 0" 0 "$r2"

sha_after="$(node -e 'const c=require("fs").readFileSync(process.argv[1]);console.log(require("crypto").createHash("sha256").update(c).digest("hex"))' "$list_path")"

assert "re-running assemble yields a byte-identical ai-x-follow-list.md (sha256)" "$sha_before" "$sha_after"

# -- Results summary -----------------------------------------------------
total=$((pass + fail))
echo ""
echo "Results: $pass / $total passed, $fail failed."
[ "$fail" -eq 0 ]
