#!/usr/bin/env bash
# Install stash-free git hooks for this single-writer vault.
#
# Why not `pre-commit install`? Its generated hook stashes every unstaged change
# to a tracked file before running, then re-applies the stash afterwards. With
# Obsidian running, .obsidian/plugins/*/{data.json,main.js,...} are rewritten
# under it, the re-apply fails ("patch does not apply") and pre-commit rolls
# back — reverting OTHER unstaged files on disk (see _CLAUDE.md, "pre-commit trap").
#
# `pre-commit run --files ...` never stashes (pre_commit/commands/run.py:
# `stash = not args.all_files and not args.files`), so these wrappers pass the
# staged file list explicitly. Trade-off: hooks see the WORKTREE content of a
# partially-staged file, not the index — acceptable for a single-writer vault.
#
# Only pre-commit and commit-msg are installed. pre-push is deliberately left
# out: the two pre-push checks are no-ops on a .single-writer repo, and hooking
# the Obsidian Git plugin's push path adds failure surface for zero benefit.
#
# Idempotent. Re-run after a fresh clone (.git/hooks is not versioned).
set -euo pipefail

root=$(git rev-parse --show-toplevel)
hooks_dir=$(git -C "$root" rev-parse --git-path hooks)
mkdir -p "$hooks_dir"

cat >"$hooks_dir/pre-commit" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/hooks/install-nostash-hooks.sh — do not edit by hand.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
mapfile -d '' -t files < <(git diff --cached --name-only --diff-filter=ACMR -z)
[ "${#files[@]}" -eq 0 ] && exit 0
exec pre-commit run --hook-stage pre-commit --files "${files[@]}"
HOOK

cat >"$hooks_dir/commit-msg" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/hooks/install-nostash-hooks.sh — do not edit by hand.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
mapfile -d '' -t files < <(git diff --cached --name-only --diff-filter=ACMR -z)
[ "${#files[@]}" -eq 0 ] && exit 0
exec pre-commit run --hook-stage commit-msg --commit-msg-filename "$1" --files "${files[@]}"
HOOK

chmod +x "$hooks_dir/pre-commit" "$hooks_dir/commit-msg"

# Warm the hook environments now, so the first real commit does not stall on
# network fetches (gitleaks, pre-commit-hooks, shellcheck-py).
(cd "$root" && pre-commit install-hooks)

echo "installed: $hooks_dir/pre-commit, $hooks_dir/commit-msg (stash-free)"
