#!/usr/bin/env bash
# Generate CHANGELOG.md from conventional-commit history (single Unreleased
# section, newest first). Non-conventional/merge/revert → ### Other.
# Fully generated; do not hand-edit. Idempotent on immediate re-run.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/CHANGELOG.md"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$SCRIPT_DIR/lib/commit-class.sh"
added=""; fixed=""; changed=""; other=""
while IFS=$'\t' read -r subj; do
    # Added/Fixed are single-type sections (the heading conveys feat/fix), so
    # strip the whole `type(scope): ` prefix → just the description (keeps the
    # `[HIMMEL-N]` + message). `${subj#*: }` removes up to & incl the first
    # `: ` (colon-space); a malformed no-space subject keeps its prefix.
    # Changed is mixed-type (chore/refactor/docs/test) so the type stays
    # informative — keep the full subject; Other keeps the raw subject.
    case "$(cc_classify "$subj")" in
        feat)    added="${added}- ${subj#*: }"$'\n';;
        fix)     fixed="${fixed}- ${subj#*: }"$'\n';;
        changed) changed="${changed}- ${subj}"$'\n';;
        *)       other="${other}- ${subj}"$'\n';;
    esac
done < <(git log --no-merges --format='%s')
# Blank line goes BEFORE each heading (not after each section) so the file
# ends with exactly one trailing newline — otherwise end-of-file-fixer rewrites
# it on every commit and a freshly regenerated file never matches the committed
# one (breaking the idempotence promise). $added/$fixed/… already end in \n, so
# the section body is emitted with `printf '%s'` (no extra trailing newline).
{
    echo "<!-- generated by scripts/gen-changelog.sh; do not hand-edit -->"
    echo "# Changelog"
    echo
    echo "## [Unreleased]"
    [ -n "$added" ]   && { echo; echo "### Added";   printf '%s' "$added"; }
    [ -n "$fixed" ]   && { echo; echo "### Fixed";   printf '%s' "$fixed"; }
    [ -n "$changed" ] && { echo; echo "### Changed"; printf '%s' "$changed"; }
    [ -n "$other" ]   && { echo; echo "### Other";   printf '%s' "$other"; }
} > "$OUT"
