# Generate CHANGELOG.md from conventional-commit history (single Unreleased
# section, newest first). Non-conventional/merge/revert -> ### Other.
# Fully generated; do not hand-edit. Idempotent on immediate re-run.
$ErrorActionPreference = 'Stop'

$root = (git rev-parse --show-toplevel 2>&1)
if ($LASTEXITCODE -ne 0) { Write-Error "Not a git repository"; exit 1 }
$out = Join-Path $root 'CHANGELOG.md'

$added   = @()
$fixed   = @()
$changed = @()
$other   = @()

# Twin of gen-changelog.sh — output MUST match byte-for-byte. The .sh strips the
# whole `type(scope): ` prefix for Added/Fixed (the heading conveys the type) and
# keeps the full subject for Changed/Other; mirror that exactly. `^[^:]*: ` =
# everything up to & incl the first colon-space, equivalent to bash `${subj#*: }`
# (a no-space subject keeps its prefix in both).
# No `2>&1`: the .sh twin lets git's stderr go to the terminal (not into the
# data) — capturing it here would inject warning lines as spurious entries.
$subjects = git log --no-merges '--format=%s'
foreach ($subj in $subjects) {
    if ($subj -match '^feat[:(]') {
        $added   += "- " + ($subj -replace '^[^:]*: ','')
    } elseif ($subj -match '^fix[:(]') {
        $fixed   += "- " + ($subj -replace '^[^:]*: ','')
    } elseif ($subj -match '^(chore|refactor|docs|test)[:(]') {
        $changed += "- $subj"
    } else {
        $other   += "- $subj"
    }
}

# Blank line BEFORE each heading (not after each section) so the file ends with
# exactly one trailing newline — matches the .sh twin and stays end-of-file-fixer
# clean (a regenerated file must equal the committed one).
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('<!-- generated by scripts/gen-changelog.sh; do not hand-edit -->')
$lines.Add('# Changelog')
$lines.Add('')
$lines.Add('## [Unreleased]')

if ($added.Count -gt 0) {
    $lines.Add(''); $lines.Add('### Added')
    foreach ($l in $added) { $lines.Add($l) }
}
if ($fixed.Count -gt 0) {
    $lines.Add(''); $lines.Add('### Fixed')
    foreach ($l in $fixed) { $lines.Add($l) }
}
if ($changed.Count -gt 0) {
    $lines.Add(''); $lines.Add('### Changed')
    foreach ($l in $changed) { $lines.Add($l) }
}
if ($other.Count -gt 0) {
    $lines.Add(''); $lines.Add('### Other')
    foreach ($l in $other) { $lines.Add($l) }
}

# Write UTF-8 (no BOM) with LF line endings + a single trailing newline, so the
# Windows twin produces byte-identical output to the bash twin (no CRLF drift).
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$text = ($lines -join "`n") + "`n"
[System.IO.File]::WriteAllText($out, $text, $utf8NoBom)
exit 0
