#!/usr/bin/env bash
# PreToolUse hook — service-agnostic backend-routing guard (HIMMEL-400).
#
# Generalises block-mcp-when-plugin-exists.sh: instead of hard-coding Jira,
# routing is driven by a registry (scripts/backends.json or BACKENDS_REGISTRY
# env override) whose per-service chain field [cli,api,mcp] determines
# precedence.  A service with chain [cli,api,mcp] hard-blocks MCP calls that
# have a known CLI equivalent (same autogenerated verb-introspection logic as
# the original Jira hook).  The `api` tier is ADVISORY only: it never triggers
# a block — it only adjusts the refusal message to mention raw REST first.
#
# Hook input arrives on stdin as JSON shaped like:
#   { "tool_name": "mcp__plugin_atlassian_atlassian__getJiraIssue",
#     "tool_input": {...} }
#
# Exit codes:
#   0 — allow
#   2 — block; stderr is shown to Claude and the user
#
# Fail modes:
#   - jq parse of the HOOK INPUT fails → fail CLOSED (exit 2). The matcher
#     routes only known MCP prefixes here; a parse failure means a contract
#     change or adversarial input — refuse rather than allow.
#   - CLI INTROSPECTION fails (node missing, CLI absent, errors, empty
#     output) → fail OPEN (allow). A broken CLI must never hard-block a
#     legit MCP call the operator may need as a fallback.
#   - Registry read/parse fails → warn to stderr + fall back to code defaults
#     (fail open on CONFIG, fail closed on INPUT as above).
#
# Bypass env vars (set in the shell that LAUNCHED Claude Code):
#   MCP_ALL_OK=1              — global; bypasses every service.
#   MCP_JIRA_OK=1             — Jira only (legacy name; still honoured).
#   MCP_<SERVICE_UPPER>_OK=1  — per-service (e.g. MCP_GITHUB_OK=1, MCP_CONFLUENCE_OK=1).
set -euo pipefail

# ---------------------------------------------------------------------------
# Code-level defaults — baked in so the hook works without a registry file.
# Each entry: <service-name>|<enabled>|<mcp_prefix>|<cli_bin>|<chain>
# chain is colon-separated tiers (cli:api:mcp or mcp:cli:api etc.)
# ---------------------------------------------------------------------------
_DEFAULTS="jira|true|mcp__plugin_atlassian_atlassian__|scripts/jira/dist/index.js|cli:api:mcp
confluence|true|mcp__plugin_atlassian_atlassian__|scripts/jira/dist/confluence.js|cli:api:mcp
bitbucket|true||scripts/bitbucket/dist/index.js|cli:api:mcp
github|true||gh|cli:api:mcp"

# ---------------------------------------------------------------------------
# Jira verb->MCP-method map (same as original hook; bash 3.2-safe tab table)
# ---------------------------------------------------------------------------
_JIRA_VERB_METHOD_MAP=$(printf '%s\n' \
    "list	searchJiraIssuesUsingJql" \
    "get	getJiraIssue" \
    "create	createJiraIssue" \
    "edit	editJiraIssue" \
    "comment	addCommentToJiraIssue" \
    "transition	transitionJiraIssue" \
    "transition	getTransitionsForJiraIssue" \
    "projects	getVisibleJiraProjects" \
    "link	createIssueLink")

# ---------------------------------------------------------------------------
# Confluence verb->MCP-method map. Verb strings match `confluence.js
# --list-commands` EXACTLY (page verbs are space-joined: "page get").
# Jira and Confluence method-name SUFFIXES are disjoint (*Jira* vs
# *Confluence*), so at most one service maps any given MCP suffix — the
# multi-service loop below can never double-attribute.
# ---------------------------------------------------------------------------
_CONFLUENCE_VERB_METHOD_MAP=$(printf '%s\n' \
    "page get	getConfluencePage" \
    "page create	createConfluencePage" \
    "page update	updateConfluencePage" \
    "search	searchConfluenceUsingCql" \
    "spaces	getConfluenceSpaces" \
    "comments	getConfluencePageFooterComments" \
    "comment	createConfluenceFooterComment")

# ---------------------------------------------------------------------------
# Replacement hint per verb, keyed by service and verb.
# Format: <service>:<verb> → human-readable replacement command.
# ---------------------------------------------------------------------------
replacement_for() {
    local service="$1" verb="$2"
    case "${service}:${verb}" in
        jira:get)        echo 'node scripts/jira/dist/index.js get HIMMEL-N' ;;
        jira:list)       echo 'node scripts/jira/dist/index.js list --jql "<your JQL>"' ;;
        jira:create)     echo 'node scripts/jira/dist/index.js create --project HIMMEL --type Story --title "..." --desc "..."' ;;
        jira:edit)       echo 'node scripts/jira/dist/index.js edit HIMMEL-N --title "..." --desc "..."' ;;
        jira:comment)    echo 'node scripts/jira/dist/index.js comment HIMMEL-N "<text>"' ;;
        jira:transition) echo 'node scripts/jira/dist/index.js transition HIMMEL-N <Status Name>' ;;
        jira:projects)   echo 'node scripts/jira/dist/index.js projects' ;;
        jira:link)       echo 'node scripts/jira/dist/index.js link HIMMEL-A HIMMEL-B --type Relates' ;;
        jira:*)          echo 'node scripts/jira/dist/index.js --help' ;;
        # Confluence — note the page verbs carry an internal space in the arm key.
        "confluence:page get")    echo 'node scripts/jira/dist/confluence.js page get <id>' ;;
        "confluence:page create") echo 'node scripts/jira/dist/confluence.js page create --space <KEY> --title "..." --body-file <f>' ;;
        "confluence:page update") echo 'node scripts/jira/dist/confluence.js page update <id> --body-file <f>' ;;
        confluence:search)        echo 'node scripts/jira/dist/confluence.js search --cql "<cql>"' ;;
        confluence:spaces)        echo 'node scripts/jira/dist/confluence.js spaces' ;;
        confluence:comments)      echo 'node scripts/jira/dist/confluence.js comments <pageId>' ;;
        confluence:comment)       echo 'node scripts/jira/dist/confluence.js comment <pageId> "<text>"' ;;
        confluence:*)             echo 'node scripts/jira/dist/confluence.js --help' ;;
        *)               echo "${service} CLI --help" ;;
    esac
}

# ---------------------------------------------------------------------------
# verb_method_map_for <service> — emit the verb<TAB>method table for a service
# ---------------------------------------------------------------------------
verb_method_map_for() {
    case "$1" in
        jira)       printf '%s\n' "$_JIRA_VERB_METHOD_MAP" ;;
        confluence) printf '%s\n' "$_CONFLUENCE_VERB_METHOD_MAP" ;;
        *)    : ;;  # no map → nothing matches → allow
    esac
}

# ---------------------------------------------------------------------------
# jq dependency check
# ---------------------------------------------------------------------------
if ! command -v jq >/dev/null 2>&1; then
    echo "block-backend-tier: jq not on PATH — refusing to evaluate; install jq or comment the hook in .claude/settings.json" >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# Read hook input; fail CLOSED on jq parse error
# ---------------------------------------------------------------------------
input=$(cat)

if ! tool_name=$(printf '%s' "$input" | jq -r '.tool_name | select(type=="string") // empty' 2>/dev/null); then
    echo "block-backend-tier: jq failed to parse hook input — refusing to evaluate (set MCP_ALL_OK=1 in launching shell to bypass)" >&2
    exit 2
fi

# Strip whitespace/CR/LF — real tool names are bare ASCII identifiers.
tool_name="${tool_name//[$' \t\r\n']/}"
[ -z "$tool_name" ] && exit 0

# ---------------------------------------------------------------------------
# Global bypass
# ---------------------------------------------------------------------------
if [ "${MCP_ALL_OK:-0}" = "1" ]; then
    exit 0
fi

# ---------------------------------------------------------------------------
# Resolve repo root (for relative CLI paths)
# ---------------------------------------------------------------------------
hook_dir=$(cd "$(dirname "$0")" && pwd)
repo_root="${CLAUDE_PROJECT_DIR:-}"
if [ -z "$repo_root" ]; then
    repo_root=$(git -C "$hook_dir" rev-parse --show-toplevel 2>/dev/null || true)
fi
[ -z "$repo_root" ] && repo_root=$(cd "$hook_dir/../.." && pwd)

# ---------------------------------------------------------------------------
# Load registry: BACKENDS_REGISTRY env (test seam) → backends.json → defaults
# ---------------------------------------------------------------------------
registry_json=""
registry_source="code-defaults"

load_registry_env="${BACKENDS_REGISTRY:-}"
if [ -n "$load_registry_env" ]; then
    if [ -f "$load_registry_env" ]; then
        registry_json=$(cat "$load_registry_env" 2>/dev/null || true)
        registry_source="$load_registry_env"
    else
        echo "block-backend-tier: BACKENDS_REGISTRY file not found: $load_registry_env — falling back to code defaults" >&2
    fi
else
    registry_file="$repo_root/scripts/backends.json"
    if [ -f "$registry_file" ]; then
        registry_json=$(cat "$registry_file" 2>/dev/null || true)
        registry_source="$registry_file"
    fi
fi

# Validate registry JSON; fall back silently to code defaults on parse failure.
if [ -n "$registry_json" ]; then
    if ! printf '%s' "$registry_json" | jq empty 2>/dev/null; then
        echo "block-backend-tier: malformed JSON in $registry_source — falling back to code defaults" >&2
        registry_json=""
        registry_source="code-defaults"
    fi
fi

# ---------------------------------------------------------------------------
# Check each service: does tool_name match its mcp_prefix?
# ---------------------------------------------------------------------------
# We iterate the service list. For code-defaults we parse the _DEFAULTS string.
# For a registry JSON file we ask jq to emit the same pipe-delimited format.
# bash 3.2-safe: no mapfile, no associative arrays.

if [ -n "$registry_json" ]; then
    # Emit: name|enabled|mcp_prefix|cli_bin|chain (colon-joined)
    services_list=$(printf '%s' "$registry_json" | jq -r '
        to_entries[] |
        .key as $name |
        .value |
        [
            $name,
            (if .enabled == false then "false" else "true" end),
            (.mcp_prefix // ""),
            (.cli // ""),
            ((.chain // ["cli","api","mcp"]) | join(":"))
        ] | join("|")
    ' 2>/dev/null) || {
        echo "block-backend-tier: jq failed to parse registry $registry_source — falling back to code defaults" >&2
        services_list=$(printf '%s\n' "$_DEFAULTS")
    }
else
    services_list=$(printf '%s\n' "$_DEFAULTS")
fi

# ---------------------------------------------------------------------------
# node-based CLI (*.js) → invoke via node; others invoke directly.
# Defined once at top level (used by evaluate_service).
# ---------------------------------------------------------------------------
invoke_cli() {
    local bin="$1"
    case "$bin" in
        *.js)
            if ! command -v node >/dev/null 2>&1; then
                return 1
            fi
            node "$bin" --list-commands 2>/dev/null
            ;;
        *)
            if ! command -v "$bin" >/dev/null 2>&1 && [ ! -f "$bin" ]; then
                return 1
            fi
            "$bin" --list-commands 2>/dev/null
            ;;
    esac
}

# ---------------------------------------------------------------------------
# evaluate_service <name> <chain> <cli> <prefix>
#   Evaluate ONE prefix-matching service. Returns:
#     2 — block (refusal already printed to stderr)
#     0 — no block for this service (caller should try the next match)
#   Reads globals: tool_name, repo_root, env bypass vars, JIRA_CLI/CONFLUENCE_CLI.
#   Every "no block" path returns 0 (NOT exit) so the multi-service loop below
#   can keep going; only a genuine block returns 2. Call it from an `if`
#   condition so `set -e` is suspended for its dynamic extent (a `return 2`
#   must not abort the script prematurely).
# ---------------------------------------------------------------------------
evaluate_service() {
    local matched_service="$1" matched_chain="$2" matched_cli="$3" matched_prefix="$4"
    local svc_upper bypass_var bypass_val
    local cli_above_mcp seen_cli api_in_chain tier chain_tiers
    local suffix verb_method_map verb map_verb map_method
    local cli_bin commands line verb_present
    local replacement bypass_var_alias api_advisory bypass_launch

    # Per-service bypass (MCP_<SERVICE_UPPER>_OK=1); legacy MCP_JIRA_OK honoured.
    # Security: eval builds a var name from svc_upper only after validating it
    # is [A-Z0-9_]+ (adversarial registry keys → no eval, no injection).
    svc_upper=$(printf '%s' "$matched_service" | tr '[:lower:]' '[:upper:]')
    bypass_var="MCP_${svc_upper}_OK"
    bypass_val=""
    case "$bypass_var" in
        MCP_JIRA_OK)      bypass_val="${MCP_JIRA_OK:-0}" ;;
        MCP_BITBUCKET_OK) bypass_val="${MCP_BITBUCKET_OK:-0}" ;;
        MCP_GITHUB_OK)    bypass_val="${MCP_GITHUB_OK:-0}" ;;
        *)
            case "$svc_upper" in
                *[!A-Z0-9_]*) ;;  # unsafe chars — skip bypass, no eval
                *) eval "bypass_val=\"\${${bypass_var}:-0}\"" ;;
            esac
            ;;
    esac
    [ "$bypass_val" = "1" ] && return 0

    # Determine if chain ranks cli ABOVE mcp (hard-block applies).
    matched_chain="${matched_chain//$'\r'/}"
    cli_above_mcp=0
    seen_cli=0
    IFS=':' read -ra chain_tiers <<< "$matched_chain"
    for tier in "${chain_tiers[@]}"; do
        tier="${tier//[$' \t\r\n']/}"
        case "$tier" in
            cli) seen_cli=1 ;;
            mcp) [ "$seen_cli" -eq 1 ] && cli_above_mcp=1 ;;
        esac
    done
    # mcp ranked at or above cli → no hard block for this service.
    [ "$cli_above_mcp" -eq 0 ] && return 0

    api_in_chain=0
    for tier in "${chain_tiers[@]}"; do
        tier="${tier//[$' \t\r\n']/}"
        [ "$tier" = "api" ] && api_in_chain=1
    done

    # Extract MCP method suffix and reverse-map to a CLI verb.
    suffix="${tool_name#"${matched_prefix}"}"
    verb_method_map=$(verb_method_map_for "$matched_service")
    [ -z "$verb_method_map" ] && return 0  # no map → no known equivalent → allow
    verb=""
    while IFS="$(printf '\t')" read -r map_verb map_method; do
        [ -z "$map_method" ] && continue
        if [ "$map_method" = "$suffix" ]; then
            verb="$map_verb"
            break
        fi
    done <<EOF
$verb_method_map
EOF
    [ -z "$verb" ] && return 0  # unmapped MCP method → allow

    # Introspect the CLI's actual verbs (fail OPEN on any introspection failure).
    cli_bin="$matched_cli"
    case "$cli_bin" in
        /*) : ;;  # absolute — keep as-is
        *)  cli_bin="$repo_root/$cli_bin" ;;
    esac
    # Test seams: JIRA_CLI / CONFLUENCE_CLI override the resolved CLI path.
    if [ "$matched_service" = "jira" ] && [ -n "${JIRA_CLI:-}" ]; then
        cli_bin="$JIRA_CLI"
    fi
    if [ "$matched_service" = "confluence" ] && [ -n "${CONFLUENCE_CLI:-}" ]; then
        cli_bin="$CONFLUENCE_CLI"
    fi

    if [ ! -f "$cli_bin" ] && ! command -v "$cli_bin" >/dev/null 2>&1; then
        return 0
    fi
    commands=$(invoke_cli "$cli_bin") || return 0
    [ -z "$commands" ] && return 0

    # Block iff the mapped verb is present — exact whole-line match. Strip only
    # CR/LF/TAB (NOT internal spaces) from both the verb and each introspected
    # line, so multi-word verbs like "page get" survive. Jira verbs have no
    # internal spaces, so this is a no-op for them.
    verb="${verb//[$'\t\r\n']/}"
    verb_present=0
    while IFS= read -r line; do
        line="${line//[$'\t\r\n']/}"
        if [ "$line" = "$verb" ]; then
            verb_present=1
            break
        fi
    done <<EOF
$commands
EOF
    [ "$verb_present" -eq 1 ] || return 0

    # Build refusal message and block (return 2).
    replacement=$(replacement_for "$matched_service" "$verb")
    bypass_var_alias=""
    api_advisory=""
    if [ "$api_in_chain" -eq 1 ]; then
        api_advisory="
For ops the CLI lacks, prefer raw REST (curl/WebFetch) before falling back to MCP.
"
    fi
    bypass_launch="${bypass_var}=1 claude"
    {
        printf 'block-backend-tier: refusing MCP call "%s".\n\n' "$tool_name"
        printf '%s plugin has an equivalent — use it instead:\n\n' "$matched_service"
        printf '    %s\n' "$replacement"
        if [ -n "$api_advisory" ]; then
            printf '\n%s\n' "$api_advisory"
        fi
        printf '\nWhy: the plugin is one shell call with --help schema, far fewer tokens than\n'
        printf 'the MCP schema fetch + response, and dogfoods code we ship. Routing is\n'
        printf 'governed by scripts/backends.json (chain: %s, cli ranked above mcp).\n\n' "$matched_chain"
        if [ -n "$bypass_var_alias" ]; then
            printf 'Bypass for a genuine carve-out: set %s=1 (or %s=1)\n' "$bypass_var" "$bypass_var_alias"
        else
            printf 'Bypass for a genuine carve-out: set %s=1\n' "$bypass_var"
        fi
        printf 'in the shell that launched Claude Code. Per-call prefix does not work;\n'
        printf 'the bypass lasts the session. Restart without the var to re-enable.\n\n'
        printf '    %s\n\n' "$bypass_launch"
        printf 'Or temporarily comment the hook stanza in .claude/settings.json.\n'
    } >&2
    return 2
}

# ---------------------------------------------------------------------------
# Evaluate EVERY service whose mcp_prefix matches tool_name (no break-on-first:
# jira + confluence share the Atlassian prefix). Block on the first matching
# service whose mapped verb its CLI has; otherwise continue. Jira/Confluence
# method suffixes are disjoint, so at most one service maps a given suffix.
# ---------------------------------------------------------------------------
while IFS='|' read -r svc_name svc_enabled svc_mcp_prefix svc_cli svc_chain; do
    # Strip \r — jq on Windows may produce CRLF output.
    svc_name="${svc_name//$'\r'/}"
    svc_enabled="${svc_enabled//$'\r'/}"
    svc_mcp_prefix="${svc_mcp_prefix//$'\r'/}"
    svc_cli="${svc_cli//$'\r'/}"
    svc_chain="${svc_chain//$'\r'/}"

    [ -z "$svc_name" ] && continue
    [ "$svc_enabled" = "false" ] && continue
    [ -z "$svc_mcp_prefix" ] && continue

    # Skip services whose prefix does not match this tool_name.
    case "$tool_name" in
        "${svc_mcp_prefix}"*) ;;
        *) continue ;;
    esac

    if evaluate_service "$svc_name" "$svc_chain" "$svc_cli" "$svc_mcp_prefix"; then
        : # returned 0 → no block for this service, try the next match
    else
        rc=$?
        [ "$rc" -eq 2 ] && exit 2
    fi
done <<EOF
$services_list
EOF

# No matching service blocked → allow
exit 0
