#!/usr/bin/env bash
# PreToolUse hook — service-agnostic backend-routing guard (HIMMEL-400).
#
# Generalises block-mcp-when-plugin-exists.sh: instead of hard-coding Jira,
# routing is driven by a registry (scripts/backends.json or BACKENDS_REGISTRY
# env override) whose per-service chain field [cli,api,mcp] determines
# precedence.  A service with chain [cli,api,mcp] hard-blocks MCP calls that
# have a known CLI equivalent (same autogenerated verb-introspection logic as
# the original Jira hook).  The `api` tier is ADVISORY only: it never triggers
# a block — it only adjusts the refusal message to mention raw REST first.
#
# Hook input arrives on stdin as JSON shaped like:
#   { "tool_name": "mcp__plugin_atlassian_atlassian__getJiraIssue",
#     "tool_input": {...} }
#
# Exit codes:
#   0 — allow
#   2 — block; stderr is shown to Claude and the user
#
# Fail modes:
#   - jq parse of the HOOK INPUT fails → fail CLOSED (exit 2). The matcher
#     routes only known MCP prefixes here; a parse failure means a contract
#     change or adversarial input — refuse rather than allow.
#   - CLI INTROSPECTION fails (node missing, CLI absent, errors, empty
#     output) → fail OPEN (allow). A broken CLI must never hard-block a
#     legit MCP call the operator may need as a fallback.
#   - Registry read/parse fails → warn to stderr + fall back to code defaults
#     (fail open on CONFIG, fail closed on INPUT as above).
#
# Bypass env vars (set in the shell that LAUNCHED Claude Code):
#   MCP_ALL_OK=1              — global; bypasses every service.
#   MCP_JIRA_OK=1             — Jira only (backward-compat alias for MCP_JIRA_OK).
#   MCP_<SERVICE_UPPER>_OK=1  — per-service (e.g. MCP_GITHUB_OK=1).
set -euo pipefail

# ---------------------------------------------------------------------------
# Code-level defaults — baked in so the hook works without a registry file.
# Each entry: <service-name>|<enabled>|<mcp_prefix>|<cli_bin>|<chain>
# chain is colon-separated tiers (cli:api:mcp or mcp:cli:api etc.)
# ---------------------------------------------------------------------------
_DEFAULTS="jira|true|mcp__plugin_atlassian_atlassian__|scripts/jira/dist/index.js|cli:api:mcp
bitbucket|true||scripts/bitbucket/dist/index.js|cli:api:mcp
github|true||gh|cli:api:mcp"

# ---------------------------------------------------------------------------
# Jira verb->MCP-method map (same as original hook; bash 3.2-safe tab table)
# ---------------------------------------------------------------------------
_JIRA_VERB_METHOD_MAP=$(printf '%s\n' \
    "list	searchJiraIssuesUsingJql" \
    "get	getJiraIssue" \
    "create	createJiraIssue" \
    "edit	editJiraIssue" \
    "comment	addCommentToJiraIssue" \
    "transition	transitionJiraIssue" \
    "transition	getTransitionsForJiraIssue" \
    "projects	getVisibleJiraProjects" \
    "link	createIssueLink")

# ---------------------------------------------------------------------------
# Replacement hint per verb, keyed by service and verb.
# Format: <service>:<verb> → human-readable replacement command.
# ---------------------------------------------------------------------------
replacement_for() {
    local service="$1" verb="$2"
    case "${service}:${verb}" in
        jira:get)        echo 'node scripts/jira/dist/index.js get HIMMEL-N' ;;
        jira:list)       echo 'node scripts/jira/dist/index.js list --jql "<your JQL>"' ;;
        jira:create)     echo 'node scripts/jira/dist/index.js create --project HIMMEL --type Story --title "..." --desc "..."' ;;
        jira:edit)       echo 'node scripts/jira/dist/index.js edit HIMMEL-N --title "..." --desc "..."' ;;
        jira:comment)    echo 'node scripts/jira/dist/index.js comment HIMMEL-N "<text>"' ;;
        jira:transition) echo 'node scripts/jira/dist/index.js transition HIMMEL-N <Status Name>' ;;
        jira:projects)   echo 'node scripts/jira/dist/index.js projects' ;;
        jira:link)       echo 'node scripts/jira/dist/index.js link HIMMEL-A HIMMEL-B --type Relates' ;;
        jira:*)          echo 'node scripts/jira/dist/index.js --help' ;;
        *)               echo "${service} CLI --help" ;;
    esac
}

# ---------------------------------------------------------------------------
# verb_method_map_for <service> — emit the verb<TAB>method table for a service
# ---------------------------------------------------------------------------
verb_method_map_for() {
    case "$1" in
        jira) printf '%s\n' "$_JIRA_VERB_METHOD_MAP" ;;
        *)    : ;;  # no map → nothing matches → allow
    esac
}

# ---------------------------------------------------------------------------
# jq dependency check
# ---------------------------------------------------------------------------
if ! command -v jq >/dev/null 2>&1; then
    echo "block-backend-tier: jq not on PATH — refusing to evaluate; install jq or comment the hook in .claude/settings.json" >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# Read hook input; fail CLOSED on jq parse error
# ---------------------------------------------------------------------------
input=$(cat)

if ! tool_name=$(printf '%s' "$input" | jq -r '.tool_name | select(type=="string") // empty' 2>/dev/null); then
    echo "block-backend-tier: jq failed to parse hook input — refusing to evaluate (set MCP_ALL_OK=1 in launching shell to bypass)" >&2
    exit 2
fi

# Strip whitespace/CR/LF — real tool names are bare ASCII identifiers.
tool_name="${tool_name//[$' \t\r\n']/}"
[ -z "$tool_name" ] && exit 0

# ---------------------------------------------------------------------------
# Global bypass
# ---------------------------------------------------------------------------
if [ "${MCP_ALL_OK:-0}" = "1" ]; then
    exit 0
fi

# ---------------------------------------------------------------------------
# Resolve repo root (for relative CLI paths)
# ---------------------------------------------------------------------------
hook_dir=$(cd "$(dirname "$0")" && pwd)
repo_root="${CLAUDE_PROJECT_DIR:-}"
if [ -z "$repo_root" ]; then
    repo_root=$(git -C "$hook_dir" rev-parse --show-toplevel 2>/dev/null || true)
fi
[ -z "$repo_root" ] && repo_root=$(cd "$hook_dir/../.." && pwd)

# ---------------------------------------------------------------------------
# Load registry: BACKENDS_REGISTRY env (test seam) → backends.json → defaults
# ---------------------------------------------------------------------------
registry_json=""
registry_source="code-defaults"

load_registry_env="${BACKENDS_REGISTRY:-}"
if [ -n "$load_registry_env" ]; then
    if [ -f "$load_registry_env" ]; then
        registry_json=$(cat "$load_registry_env" 2>/dev/null || true)
        registry_source="$load_registry_env"
    else
        echo "block-backend-tier: BACKENDS_REGISTRY file not found: $load_registry_env — falling back to code defaults" >&2
    fi
else
    registry_file="$repo_root/scripts/backends.json"
    if [ -f "$registry_file" ]; then
        registry_json=$(cat "$registry_file" 2>/dev/null || true)
        registry_source="$registry_file"
    fi
fi

# Validate registry JSON; fall back silently to code defaults on parse failure.
if [ -n "$registry_json" ]; then
    if ! printf '%s' "$registry_json" | jq empty 2>/dev/null; then
        echo "block-backend-tier: malformed JSON in $registry_source — falling back to code defaults" >&2
        registry_json=""
        registry_source="code-defaults"
    fi
fi

# ---------------------------------------------------------------------------
# Check each service: does tool_name match its mcp_prefix?
# ---------------------------------------------------------------------------
# We iterate the service list. For code-defaults we parse the _DEFAULTS string.
# For a registry JSON file we ask jq to emit the same pipe-delimited format.
# bash 3.2-safe: no mapfile, no associative arrays.

if [ -n "$registry_json" ]; then
    # Emit: name|enabled|mcp_prefix|cli_bin|chain (colon-joined)
    services_list=$(printf '%s' "$registry_json" | jq -r '
        to_entries[] |
        .key as $name |
        .value |
        [
            $name,
            (if .enabled == false then "false" else "true" end),
            (.mcp_prefix // ""),
            (.cli // ""),
            ((.chain // ["cli","api","mcp"]) | join(":"))
        ] | join("|")
    ' 2>/dev/null) || {
        echo "block-backend-tier: jq failed to parse registry $registry_source — falling back to code defaults" >&2
        services_list=$(printf '%s\n' "$_DEFAULTS")
    }
else
    services_list=$(printf '%s\n' "$_DEFAULTS")
fi

# Iterate services
matched_service=""
matched_chain=""
matched_cli=""
matched_prefix=""

while IFS='|' read -r svc_name svc_enabled svc_mcp_prefix svc_cli svc_chain; do
    # Strip \r from values — jq on Windows may produce CRLF output.
    svc_name="${svc_name//$'\r'/}"
    svc_enabled="${svc_enabled//$'\r'/}"
    svc_mcp_prefix="${svc_mcp_prefix//$'\r'/}"
    svc_cli="${svc_cli//$'\r'/}"
    svc_chain="${svc_chain//$'\r'/}"

    [ -z "$svc_name" ] && continue

    # Skip disabled services
    [ "$svc_enabled" = "false" ] && continue

    # Skip services with no MCP prefix (no Atlassian-style MCP namespace → nothing to match)
    [ -z "$svc_mcp_prefix" ] && continue

    # Does the tool_name start with this service's prefix?
    case "$tool_name" in
        "${svc_mcp_prefix}"*)
            matched_service="$svc_name"
            matched_prefix="$svc_mcp_prefix"
            matched_chain="$svc_chain"
            matched_cli="$svc_cli"
            break
            ;;
    esac
done <<EOF
$services_list
EOF

# No prefix matched → allow
[ -z "$matched_service" ] && exit 0

# Per-service bypass (MCP_<SERVICE_UPPER>_OK=1)
# Also honour legacy MCP_JIRA_OK=1 for the jira service.
svc_upper=$(printf '%s' "$matched_service" | tr '[:lower:]' '[:upper:]')
bypass_var="MCP_${svc_upper}_OK"
# Use indirect lookup that is bash 3.2-safe.
# Security: eval is used to build a variable name from svc_upper.  Before
# eval, we validate that svc_upper contains ONLY [A-Z0-9_] — if it holds
# any other character (possible if a registry file has an adversarial key)
# we skip the bypass (no eval, no expansion, no injection).  The explicit
# case arms below cover the known services without any eval.
bypass_val=""
case "$bypass_var" in
    MCP_JIRA_OK)      bypass_val="${MCP_JIRA_OK:-0}" ;;
    MCP_BITBUCKET_OK) bypass_val="${MCP_BITBUCKET_OK:-0}" ;;
    MCP_GITHUB_OK)    bypass_val="${MCP_GITHUB_OK:-0}" ;;
    # Generic fallback for services added via the registry.
    # eval is safe ONLY when bypass_var contains [A-Z0-9_]+ (validated below).
    *)
        case "$svc_upper" in
            *[!A-Z0-9_]*)
                # Service name contains unsafe characters — skip bypass, no eval.
                ;;
            *)
                eval "bypass_val=\"\${${bypass_var}:-0}\""
                ;;
        esac
        ;;
esac
[ "$bypass_val" = "1" ] && exit 0

# ---------------------------------------------------------------------------
# Determine if chain ranks cli ABOVE mcp (hard-block applies)
# ---------------------------------------------------------------------------
# Strip \r from matched_chain — jq on Windows may emit CRLF line endings,
# producing e.g. "cli:api:mcp\r" which breaks the case arm matching "mcp".
matched_chain="${matched_chain//$'\r'/}"
cli_above_mcp=0
seen_cli=0
IFS=':' read -ra chain_tiers <<< "$matched_chain"
for tier in "${chain_tiers[@]}"; do
    # Strip any residual whitespace from tier name (defensive)
    tier="${tier//[$' \t\r\n']/}"
    case "$tier" in
        cli) seen_cli=1 ;;
        mcp)
            # If we've already seen cli before hitting mcp, cli is ranked higher
            [ "$seen_cli" -eq 1 ] && cli_above_mcp=1
            ;;
    esac
done

# If mcp is ranked at or above cli, no hard block for this service
[ "$cli_above_mcp" -eq 0 ] && exit 0

# Check if api advisory tier is present in the chain
api_in_chain=0
for tier in "${chain_tiers[@]}"; do
    tier="${tier//[$' \t\r\n']/}"
    [ "$tier" = "api" ] && api_in_chain=1
done

# ---------------------------------------------------------------------------
# Extract MCP method suffix and reverse-map to CLI verb
# ---------------------------------------------------------------------------
suffix="${tool_name#"${matched_prefix}"}"

verb_method_map=$(verb_method_map_for "$matched_service")
if [ -z "$verb_method_map" ]; then
    # No verb map for this service → no known equivalent → allow
    exit 0
fi

verb=""
while IFS="$(printf '\t')" read -r map_verb map_method; do
    [ -z "$map_method" ] && continue
    if [ "$map_method" = "$suffix" ]; then
        verb="$map_verb"
        break
    fi
done <<EOF
$verb_method_map
EOF

# Unmapped MCP method → no plugin equivalent → allow
[ -z "$verb" ] && exit 0

# ---------------------------------------------------------------------------
# Introspect the CLI's actual verbs (fail OPEN on any introspection failure)
# ---------------------------------------------------------------------------
# Resolve CLI path: relative paths resolved from repo_root; absolute pass-through.
cli_bin="$matched_cli"
case "$cli_bin" in
    /*) : ;;  # absolute — keep as-is
    *)  cli_bin="$repo_root/$cli_bin" ;;
esac

# Allow test seam: JIRA_CLI overrides the jira service CLI path (backward compat).
if [ "$matched_service" = "jira" ] && [ -n "${JIRA_CLI:-}" ]; then
    cli_bin="$JIRA_CLI"
fi

# node-based CLI (*.js) → invoke via node; others invoke directly.
invoke_cli() {
    local bin="$1"
    case "$bin" in
        *.js)
            if ! command -v node >/dev/null 2>&1; then
                return 1
            fi
            node "$bin" --list-commands 2>/dev/null
            ;;
        *)
            if ! command -v "$bin" >/dev/null 2>&1 && [ ! -f "$bin" ]; then
                return 1
            fi
            "$bin" --list-commands 2>/dev/null
            ;;
    esac
}

if [ ! -f "$cli_bin" ] && ! command -v "$cli_bin" >/dev/null 2>&1; then
    exit 0
fi

commands=$(invoke_cli "$cli_bin") || exit 0
[ -z "$commands" ] && exit 0

# Block iff the mapped verb is present — exact whole-line match.
verb_present=0
while IFS= read -r line; do
    line="${line//[$' \t\r\n']/}"
    if [ "$line" = "$verb" ]; then
        verb_present=1
        break
    fi
done <<EOF
$commands
EOF

[ "$verb_present" -eq 1 ] || exit 0

# ---------------------------------------------------------------------------
# Build refusal message and block (exit 2)
# ---------------------------------------------------------------------------
replacement=$(replacement_for "$matched_service" "$verb")

# Determine bypass var names for the message.
# bypass_var (MCP_${svc_upper}_OK) is already set above and is used for the
# copy-pasteable command example.  For jira, the legacy alias MCP_JIRA_OK is
# the same value (svc_upper=JIRA), so no alias note is needed.
# bypass_var_alias holds an optional parenthetical alias note (non-empty only
# when the service has a well-known alternative name).
bypass_var_alias=""
# Currently no service has a *different* alias var; the old jira display was
# "MCP_JIRA_OK (or MCP_JIRA_OK)" which was redundant and garbled.  Leave the
# slot here for future services that genuinely need one.

api_advisory=""
if [ "$api_in_chain" -eq 1 ]; then
    api_advisory="
For ops the CLI lacks, prefer raw REST (curl/WebFetch) before falling back to MCP.
"
fi

# Use printf to avoid unquoted heredoc expansion of untrusted tool_name content.
# All user-data variables are passed as %s arguments, not embedded in a format string.
bypass_launch="${bypass_var}=1 claude"
{
    printf 'block-backend-tier: refusing MCP call "%s".\n\n' "$tool_name"
    printf '%s plugin has an equivalent — use it instead:\n\n' "$matched_service"
    printf '    %s\n' "$replacement"
    if [ -n "$api_advisory" ]; then
        printf '\n%s\n' "$api_advisory"
    fi
    printf '\nWhy: the plugin is one shell call with --help schema, far fewer tokens than\n'
    printf 'the MCP schema fetch + response, and dogfoods code we ship. Routing is\n'
    printf 'governed by scripts/backends.json (chain: %s, cli ranked above mcp).\n\n' "$matched_chain"
    if [ -n "$bypass_var_alias" ]; then
        printf 'Bypass for a genuine carve-out: set %s=1 (or %s=1)\n' "$bypass_var" "$bypass_var_alias"
    else
        printf 'Bypass for a genuine carve-out: set %s=1\n' "$bypass_var"
    fi
    printf 'in the shell that launched Claude Code. Per-call prefix does not work;\n'
    printf 'the bypass lasts the session. Restart without the var to re-enable.\n\n'
    printf '    %s\n\n' "$bypass_launch"
    printf 'Or temporarily comment the hook stanza in .claude/settings.json.\n'
} >&2
exit 2
