#!/usr/bin/env bash
# PreToolUse hook for MCP tool calls.
#
# Refuses Atlassian-MCP Jira tool calls when an equivalent exists in the
# local himmel-jira CLI plugin (scripts/jira/dist/index.js). The plugin is
# cheaper per call (no MCP schema fetch) and dogfoods code we ship, so
# CLAUDE.md mandates plugin-first for Jira ops with named carve-outs.
#
# Blocked-set is AUTOGENERATED (HIMMEL-231): the hook introspects the jira
# CLI's verbs via `node <cli> --list-commands` and blocks an Atlassian MCP
# method iff its mapped CLI verb appears in that list. The only remaining
# hand-maintained literal is the verb→MCP-method semantic map below — there
# is no standalone hardcoded list of blocked MCP ops independent of the
# CLI's actual verbs, so the set can no longer drift out of sync when the
# CLI gains or loses a verb.
#
# Hook input arrives on stdin as JSON shaped like:
#   { "tool_name": "mcp__plugin_atlassian_atlassian__getJiraIssue",
#     "tool_input": {...} }
#
# Exit codes:
#   0 — allow (default for non-blocked tool_names, missing field, etc.)
#   2 — block; stderr is shown to Claude and the user
#
# Fail modes:
#   - jq parse of the HOOK INPUT fails → fail CLOSED (exit 2). The matcher
#     only routes Atlassian MCP calls here; a parse failure means a Claude
#     Code contract change or adversarial input — refuse rather than allow.
#   - CLI INTROSPECTION fails (node missing, --list-commands errors, empty
#     output) → fail OPEN (allow). A broken/absent CLI must never hard-block
#     a legit MCP call the operator may need as a fallback.
#
# Bypass: set MCP_JIRA_OK=1 in the shell that LAUNCHED Claude Code (the
# hook reads its environment — per-call prefix syntax does not work
# because Claude cannot inject env vars into hook processes). Lasts the
# session.
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
    echo "block-mcp-when-plugin-exists: jq not on PATH — refusing to evaluate; install jq or comment the hook in .claude/settings.json" >&2
    exit 2
fi

input=$(cat)

# Fail CLOSED on jq parse errors. The matcher in .claude/settings.json
# only routes Atlassian MCP tool calls here, so a parse failure means
# either a Claude Code contract change or a malformed/adversarial input
# — either way, refuse to evaluate rather than silently allowing the
# call through. `select(type=="string")` guards against tool_name being
# a non-string JSON value (number, object, etc) which `jq -r` would
# otherwise stringify into something that could match a case arm.
if ! tool_name=$(printf '%s' "$input" | jq -r '.tool_name | select(type=="string") // empty' 2>/dev/null); then
    echo "block-mcp-when-plugin-exists: jq failed to parse hook input — refusing to evaluate (set MCP_JIRA_OK=1 in launching shell to bypass)" >&2
    exit 2
fi

# Strip whitespace/CR/LF anywhere in tool_name. Real Claude tool names
# are bare ASCII identifiers ([A-Za-z0-9_]+), so this is loss-free. Without
# the strip, a tool_name like "...getJiraIssue\r" would slip past the
# exact-match map lookup below and bypass the block.
tool_name="${tool_name//[$' \t\r\n']/}"

[ -z "$tool_name" ] && exit 0

# Bypass — honour before any name check so operators never see noisy
# "considered blocking" stderr when the call will succeed anyway.
if [ "${MCP_JIRA_OK:-0}" = "1" ]; then
    exit 0
fi

# Strip the Atlassian MCP prefix; any other tool_name falls through to
# the default-allow path.
suffix=""
case "$tool_name" in
    mcp__plugin_atlassian_atlassian__*)
        suffix="${tool_name#mcp__plugin_atlassian_atlassian__}"
        ;;
    *)
        exit 0
        ;;
esac

# --- Verb → MCP-method semantic map (THE only hand-maintained literal) ---
#
# bash 3.2-safe: no associative arrays. A newline-delimited
# "<cli-verb><TAB><mcp-method>" table. Several MCP methods can map to one
# verb (e.g. transition covers both getTransitionsForJiraIssue and
# transitionJiraIssue) — list one row per method. An Atlassian MCP method
# absent from this table has no plugin equivalent (Confluence, account-id
# lookup, custom-field metadata, link types, worklog, etc.) → allow.
VERB_METHOD_MAP=$(printf '%s\n' \
    "list	searchJiraIssuesUsingJql" \
    "get	getJiraIssue" \
    "create	createJiraIssue" \
    "edit	editJiraIssue" \
    "comment	addCommentToJiraIssue" \
    "transition	transitionJiraIssue" \
    "transition	getTransitionsForJiraIssue" \
    "projects	getVisibleJiraProjects" \
    "link	createIssueLink")

# Replacement-hint strings, keyed by CLI verb. Reminder beats block:
# Claude is far more likely to switch when the replacement is one paste
# away than when it has to re-derive the syntax from CLAUDE.md.
replacement_for_verb() {
    case "$1" in
        get)        echo 'node scripts/jira/dist/index.js get HIMMEL-N' ;;
        list)       echo 'node scripts/jira/dist/index.js list --jql "<your JQL>"' ;;
        create)     echo 'node scripts/jira/dist/index.js create --project HIMMEL --type Story --title "..." --desc "..."' ;;
        edit)       echo 'node scripts/jira/dist/index.js edit HIMMEL-N --title "..." --desc "..."' ;;
        comment)    echo 'node scripts/jira/dist/index.js comment HIMMEL-N "<text>"' ;;
        transition) echo 'node scripts/jira/dist/index.js transition HIMMEL-N <Status Name>' ;;
        projects)   echo 'node scripts/jira/dist/index.js projects' ;;
        link)       echo 'node scripts/jira/dist/index.js link HIMMEL-A HIMMEL-B --type Relates' ;;
        *)          echo 'node scripts/jira/dist/index.js --help' ;;
    esac
}

# Look up the CLI verb this MCP method maps to. Empty → no plugin
# equivalent → allow.
verb=""
while IFS="$(printf '\t')" read -r map_verb map_method; do
    [ -z "$map_method" ] && continue
    if [ "$map_method" = "$suffix" ]; then
        verb="$map_verb"
        break
    fi
done <<EOF
$VERB_METHOD_MAP
EOF

# Unmapped Atlassian method → no plugin equivalent → allow.
[ -z "$verb" ] && exit 0

# --- Introspect the jira CLI's actual verbs (autogenerated blocked-set) ---
#
# Resolve the repo root robustly — the hook may run from any cwd.
# CLAUDE_PROJECT_DIR is set by Claude Code; fall back to git toplevel, then
# to the hook's own location (../.. from scripts/hooks/).
hook_dir=$(cd "$(dirname "$0")" && pwd)
repo_root="${CLAUDE_PROJECT_DIR:-}"
if [ -z "$repo_root" ]; then
    repo_root=$(git -C "$hook_dir" rev-parse --show-toplevel 2>/dev/null || true)
fi
[ -z "$repo_root" ] && repo_root=$(cd "$hook_dir/../.." && pwd)

# JIRA_CLI lets the smoke test point at a fixture --list-commands emitter
# so the test never depends on a real build. Default: the built CLI.
jira_cli="${JIRA_CLI:-$repo_root/scripts/jira/dist/index.js}"

# FAIL OPEN on any introspection failure: node missing, CLI absent, the
# flag errors, or empty output. A broken/missing CLI must NOT hard-block a
# legit MCP call. One invocation, fast.
if ! command -v node >/dev/null 2>&1; then
    exit 0
fi
if [ ! -f "$jira_cli" ]; then
    exit 0
fi
commands=$(node "$jira_cli" --list-commands 2>/dev/null) || exit 0
[ -z "$commands" ] && exit 0

# Block iff the mapped verb is present in the introspected command list.
# Exact whole-line match so e.g. "transition" does not match "transitions".
verb_present=0
while IFS= read -r line; do
    line="${line//[$' \t\r\n']/}"
    if [ "$line" = "$verb" ]; then
        verb_present=1
        break
    fi
done <<EOF
$commands
EOF

[ "$verb_present" -eq 1 ] || exit 0

replacement=$(replacement_for_verb "$verb")

cat >&2 <<EOF
⛔ block-mcp-when-plugin-exists: refusing MCP call \`$tool_name\`.

himmel-jira plugin has an equivalent — use it instead:

    $replacement

Why: the plugin is one shell call with --help schema, ~50 tokens per
invocation vs. ~2-5K for the MCP schema fetch, and dogfoods code we
ship. CLAUDE.md \`Jira tooling — prefer plugin over MCP\` documents the
full mapping.

Bypass for a genuine carve-out (custom-field discovery, account-id
lookup, etc. — see CLAUDE.md): set MCP_JIRA_OK=1 in the shell that
launched Claude Code. Per-call prefix does not work; the bypass lasts
the session. Restart without the var to re-enable.

    MCP_JIRA_OK=1 claude

Or temporarily comment the hook stanza in .claude/settings.json.
EOF
exit 2
