#!/usr/bin/env bash
# Pre-push hook: run `npm audit` on every top-level package.json in the repo.
# Blocks push on high or critical production-dep vulnerabilities.
set -euo pipefail

# Enumerates EVERY committed package.json via `git ls-files` (tracked files
# only), so plugins under marketplace/ and plugins/ are covered too — not just
# the packages under scripts/. The node_modules pathspec exclude is defensive:
# `git ls-files` already omits untracked nested worktrees + dependency trees.
if ! pkgs_raw=$(git ls-files '*package.json' ':(exclude)*/node_modules/*'); then
    echo "ERROR: 'git ls-files' failed — cannot enumerate packages to audit." >&2
    exit 1
fi
pkgs=()
if [ -n "$pkgs_raw" ]; then
    # bash 3.2-safe (macOS): no mapfile.
    while IFS= read -r _line; do pkgs+=("$_line"); done <<<"$pkgs_raw"
fi

if [ ${#pkgs[@]} -eq 0 ]; then
    echo "→ npm audit: no committed package.json found — nothing to audit"
    exit 0
fi

fail=0
for pkg in "${pkgs[@]}"; do
    dir=$(dirname "$pkg")

    # Bun-package detection: skip if a bun lockfile is present (bun.lock or
    # bun.lockb — generated by `bun install`, often gitignored but present on
    # the developer's machine), OR if the package.json scripts invoke `bun install`
    # directly (reliable signal for fresh checkouts where bun.lock is gitignored).
    if [ -f "$dir/bun.lock" ] || [ -f "$dir/bun.lockb" ]; then
        echo "→ npm audit: skipping $dir — bun lockfile present (not an npm package)"
        continue
    fi
    if grep -q '"bun install' "$dir/package.json" 2>/dev/null; then
        echo "→ npm audit: skipping $dir — package.json scripts use 'bun install' (bun package, not npm)"
        continue
    fi

    # Self-install prod deps when node_modules is missing (e.g. fresh worktree).
    # --ignore-scripts is critical: never execute third-party postinstall scripts in a pre-push gate.
    if [ ! -d "$dir/node_modules" ]; then
        if [ -f "$dir/package-lock.json" ]; then
            echo "→ npm audit: node_modules missing in $dir — running 'npm ci --omit=dev --ignore-scripts'"
            if ! (cd "$dir" && npm ci --omit=dev --ignore-scripts); then
                echo "ERROR: 'npm ci --omit=dev --ignore-scripts' failed in $dir — cannot npm audit." >&2
                echo "       The install itself broke; fix it (e.g. lockfile drift, registry auth) before pushing." >&2
                fail=1
                continue
            fi
        else
            echo "ERROR: no package-lock.json in $dir — cannot npm audit." >&2
            echo "       Generate it first: npm install --package-lock-only (in $dir)" >&2
            fail=1
            continue
        fi
    fi
    echo "→ npm audit in $dir"
    if ! (cd "$dir" && npm audit --omit=dev --audit-level=high); then
        fail=1
    fi
done

if [ $fail -ne 0 ]; then
    echo ""
    echo "ERROR: npm audit found high/critical vulnerabilities. Push blocked."
    echo "       Run \`npm audit fix\` or \`npm audit --omit=dev\` in the affected package."
fi

exit $fail
