#!/usr/bin/env bash
# Pre-push hook: run `npm audit` on every top-level package.json in the repo.
# Blocks push on high or critical production-dep vulnerabilities.
set -euo pipefail

# Enumerates EVERY committed package.json via `git ls-files` (tracked files
# only), so plugins under marketplace/ and plugins/ are covered too — not just
# the packages under scripts/. The node_modules pathspec exclude is defensive:
# `git ls-files` already omits untracked nested worktrees + dependency trees.
# Bench FIXTURES are excluded (HIMMEL-1723): their package.json/lockfiles are
# benchmark INPUTS — deliberately incomplete or stale as part of the task —
# and `npm audit` completing an incomplete fixture lockfile MUTATES fixture
# bytes mid-push (the stash-conflict abort this exclusion fixes).
if ! pkgs_raw=$(git ls-files '*package.json' ':(exclude)*/node_modules/*' ':(exclude)scripts/lanes/bench/fixtures/*'); then
    echo "ERROR: 'git ls-files' failed — cannot enumerate packages to audit." >&2
    exit 1
fi
pkgs=()
if [ -n "$pkgs_raw" ]; then
    # bash 3.2-safe (macOS): no mapfile.
    while IFS= read -r _line; do pkgs+=("$_line"); done <<<"$pkgs_raw"
fi

if [ ${#pkgs[@]} -eq 0 ]; then
    echo "→ npm audit: no committed package.json found — nothing to audit"
    exit 0
fi

# Matches the registry/transport-error shapes seen in practice (HIMMEL-2972):
# npm's own "audit endpoint returned an error", a raw 'Bad Request', the
# ENOAUDIT/ENOTFOUND/ECONNREFUSED/ECONNRESET/ETIMEDOUT error codes, or an
# npm error-code line naming a 4xx/5xx registry status. Anything else stays
# on the original fail-closed (vulnerabilities) path — never guessed.
is_transport_error() {
    # here-string, not `printf | grep -q` — under `set -o pipefail`, grep -q
    # exiting on first match SIGPIPEs a piped producer, and pipefail can then
    # report the pipeline as failed even though the match succeeded
    # (HIMMEL-1430). A here-string has no producer process to SIGPIPE.
    grep -Eqi \
        'audit endpoint returned an error|ENOAUDIT|ENOTFOUND|ECONNREFUSED|ECONNRESET|ETIMEDOUT|Bad Request|code E[45][0-9]{2}' \
        <<< "$1"
}

fail=0
indeterminate=0
for pkg in "${pkgs[@]}"; do
    dir=$(dirname "$pkg")

    # Bun-package detection: skip if a bun lockfile is present (bun.lock or
    # bun.lockb — generated by `bun install`, often gitignored but present on
    # the developer's machine), OR if the package.json scripts invoke `bun install`
    # directly (reliable signal for fresh checkouts where bun.lock is gitignored).
    if [ -f "$dir/bun.lock" ] || [ -f "$dir/bun.lockb" ]; then
        echo "→ npm audit: skipping $dir — bun lockfile present (not an npm package)"
        continue
    fi
    if grep -q '"bun install' "$dir/package.json" 2>/dev/null; then
        echo "→ npm audit: skipping $dir — package.json scripts use 'bun install' (bun package, not npm)"
        continue
    fi

    # Self-install prod deps when node_modules is missing (e.g. fresh worktree).
    # --ignore-scripts is critical: never execute third-party postinstall scripts in a pre-push gate.
    if [ ! -d "$dir/node_modules" ]; then
        if [ -f "$dir/package-lock.json" ]; then
            echo "→ npm audit: node_modules missing in $dir — running 'npm ci --omit=dev --ignore-scripts'"
            if ! (cd "$dir" && npm ci --omit=dev --ignore-scripts); then
                echo "ERROR: 'npm ci --omit=dev --ignore-scripts' failed in $dir — cannot npm audit." >&2
                echo "       The install itself broke; fix it (e.g. lockfile drift, registry auth) before pushing." >&2
                fail=1
                continue
            fi
        else
            echo "ERROR: no package-lock.json in $dir — cannot npm audit." >&2
            echo "       Generate it first: npm install --package-lock-only (in $dir)" >&2
            fail=1
            continue
        fi
    fi
    echo "→ npm audit in $dir"
    # `if var=$(...)` guards the assignment from `set -e` — a bare
    # `var=$(failing_cmd)` statement would abort the whole script under -e.
    audit_rc=0
    if audit_out=$(cd "$dir" && npm audit --omit=dev --audit-level=high 2>&1); then
        :
    else
        audit_rc=$?
    fi
    echo "$audit_out"
    if [ $audit_rc -ne 0 ] && is_transport_error "$audit_out"; then
        echo "→ npm audit: registry error in $dir, retrying..."
        # if-guarded, not `&& sleep`, so a 0 override still runs (test seam).
        if [ "${NPM_AUDIT_RETRY_SLEEP:-3}" -gt 0 ]; then
            sleep "${NPM_AUDIT_RETRY_SLEEP:-3}"
        fi
        audit_rc=0
        if retry_out=$(cd "$dir" && npm audit --omit=dev --audit-level=high 2>&1); then
            :
        else
            audit_rc=$?
        fi
        echo "$retry_out"
        if [ $audit_rc -eq 0 ]; then
            echo "→ npm audit: registry error in $dir, retry succeeded"
        else
            indeterminate=1
            registry=$(cd "$dir" && npm config get registry 2>/dev/null) || registry="(unknown — npm config get registry failed)"
            echo "ERROR: npm audit could not reach the registry for $dir (retry) — audit is INDETERMINATE, not a vulnerability finding" >&2
            echo "       registry: $registry" >&2
        fi
    elif [ $audit_rc -ne 0 ]; then
        fail=1
    fi
done

if [ $fail -ne 0 ]; then
    echo ""
    echo "ERROR: npm audit found high/critical vulnerabilities. Push blocked."
    echo "       Run \`npm audit fix\` or \`npm audit --omit=dev\` in the affected package."
fi

if [ $fail -ne 0 ] || [ $indeterminate -ne 0 ]; then
    exit 1
fi
exit 0
