#!/usr/bin/env bash
# Smoke test for scripts/hooks/block-mcp-when-plugin-exists.sh.
#
# The blocked-set is AUTOGENERATED from the jira CLI's verbs (HIMMEL-231).
# This test drives the hook with a STUB CLI via JIRA_CLI so it never
# depends on a real build: the stub's `--list-commands` output IS the
# verb list, so adding/removing a verb in the fixture changes the
# blocked-set with NO hook edit. That is the property under test.
#
# Usage: bash scripts/hooks/test-block-mcp-when-plugin-exists.sh
#
# Exit codes:
#   0 — all cases passed
#   1 — at least one case failed
set -uo pipefail

HOOK="$(cd "$(dirname "$0")" && pwd)/block-mcp-when-plugin-exists.sh"
[ -x "$HOOK" ] || chmod +x "$HOOK"

# --- Stub CLI factory ---------------------------------------------------
# Build throwaway "jira CLI" scripts that emit a fixed verb list on
# --list-commands. The stubs are node scripts (the hook calls them via
# `node "$jira_cli"`), so node must be on PATH for this test — same
# dependency the real hook has.
TMPDIR_TEST=$(mktemp -d)
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# make_stub <path> <verb>...  — emits each verb on its own line for
# --list-commands and exits 0; any other argv exits 1.
make_stub() {
    local path="$1"; shift
    {
        echo '#!/usr/bin/env node'
        echo 'if (process.argv.includes("--list-commands")) {'
        for verb in "$@"; do
            echo "  console.log(\"$verb\");"
        done
        echo '  process.exit(0);'
        echo '}'
        echo 'process.exit(1);'
    } > "$path"
}

# Full verb set (mirrors the real CLI today).
STUB_FULL="$TMPDIR_TEST/cli-full.js"
make_stub "$STUB_FULL" get create list transition transitions comment \
    attach edit move projects project-create link

# Reduced verb set: 'link' and 'create' REMOVED — proves removing a verb
# from the introspected list removes the corresponding MCP method from the
# blocked-set with NO hook edit.
STUB_REDUCED="$TMPDIR_TEST/cli-reduced.js"
make_stub "$STUB_REDUCED" get list transition comment edit projects

# A stub that ERRORS (exits non-zero) on --list-commands — introspection
# failure → fail open.
STUB_ERR="$TMPDIR_TEST/cli-err.js"
{
    echo '#!/usr/bin/env node'
    echo 'process.exit(3);'
} > "$STUB_ERR"

# A stub that emits NOTHING on --list-commands but exits 0 — empty output
# → fail open.
STUB_EMPTY="$TMPDIR_TEST/cli-empty.js"
{
    echo '#!/usr/bin/env node'
    echo 'process.exit(0);'
} > "$STUB_EMPTY"

# Only 'transitions' (NOT 'transition') present — substring guard fixture.
STUB_TRANS_ONLY="$TMPDIR_TEST/cli-transitions-only.js"
make_stub "$STUB_TRANS_ONLY" get transitions

run_case() {
    local input="$1"
    local cli="${2:-$STUB_FULL}"
    local extra_env="${3:-}"
    if [ -n "$extra_env" ]; then
        printf '%s' "$input" | env "JIRA_CLI=$cli" "$extra_env" bash "$HOOK" >/dev/null 2>&1
    else
        printf '%s' "$input" | env "JIRA_CLI=$cli" bash "$HOOK" >/dev/null 2>&1
    fi
    echo "$?"
}

assert_rc() {
    local label="$1" expected="$2" actual="$3"
    if [ "$actual" = "$expected" ]; then
        echo "PASS $label (rc=$actual)"
    else
        echo "FAIL $label — expected rc=$expected, got rc=$actual"
        FAILED=$((FAILED + 1))
    fi
}

# Assert the rendered stderr block contains the expected plugin command.
assert_stderr_contains() {
    local label="$1" input="$2" needle="$3"
    local out
    out=$(printf '%s' "$input" | env "JIRA_CLI=$STUB_FULL" bash "$HOOK" 2>&1 >/dev/null || true)
    case "$out" in
        *"$needle"*) echo "PASS $label" ;;
        *)
            echo "FAIL $label — stderr missing: $needle"
            echo "--- got ---"
            echo "$out"
            echo "-----------"
            FAILED=$((FAILED + 1))
            ;;
    esac
}

FAILED=0

# --- Blocked tools (mapped verb present in FULL introspected set) ---
for tool in getJiraIssue searchJiraIssuesUsingJql createJiraIssue \
            editJiraIssue addCommentToJiraIssue getTransitionsForJiraIssue \
            transitionJiraIssue getVisibleJiraProjects createIssueLink; do
    rc=$(run_case "{\"tool_name\":\"mcp__plugin_atlassian_atlassian__${tool}\",\"tool_input\":{}}")
    assert_rc "block $tool (verb present)" 2 "$rc"
done

# --- Autogeneration property: REMOVE verbs from the fixture, blocked-set
# shrinks with NO hook edit. With 'link'+'create' gone, createIssueLink
# and createJiraIssue must now be ALLOWED; the rest still blocked. ---
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__createIssueLink","tool_input":{}}' "$STUB_REDUCED")
assert_rc "allow createIssueLink when 'link' verb absent" 0 "$rc"
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__createJiraIssue","tool_input":{}}' "$STUB_REDUCED")
assert_rc "allow createJiraIssue when 'create' verb absent" 0 "$rc"
# Still-present verbs stay blocked under the reduced fixture.
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' "$STUB_REDUCED")
assert_rc "block getJiraIssue when 'get' verb still present" 2 "$rc"

# --- 'transition' verb maps from TWO MCP methods; both gated on one verb.
# Under reduced fixture (transition present) both still block. ---
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__transitionJiraIssue","tool_input":{}}' "$STUB_REDUCED")
assert_rc "block transitionJiraIssue (transition present)" 2 "$rc"
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getTransitionsForJiraIssue","tool_input":{}}' "$STUB_REDUCED")
assert_rc "block getTransitionsForJiraIssue (transition present)" 2 "$rc"

# --- Substring guard: a fixture verb 'transitions' must NOT make the
# 'transition'-mapped methods block on its own. Only 'transitions'
# present (no 'transition') → transitionJiraIssue ALLOWED. ---
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__transitionJiraIssue","tool_input":{}}' "$STUB_TRANS_ONLY")
assert_rc "allow transitionJiraIssue when only 'transitions' present (no substring match)" 0 "$rc"

# --- Stderr quality: each refusal must include the plugin verb ---
assert_stderr_contains "stderr names 'get' verb" \
    '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' \
    'jira/dist/index.js get'
assert_stderr_contains "stderr names 'transition' verb" \
    '{"tool_name":"mcp__plugin_atlassian_atlassian__transitionJiraIssue","tool_input":{}}' \
    'jira/dist/index.js transition'
assert_stderr_contains "stderr names 'list' verb for JQL" \
    '{"tool_name":"mcp__plugin_atlassian_atlassian__searchJiraIssuesUsingJql","tool_input":{}}' \
    'jira/dist/index.js list'
assert_stderr_contains "stderr names 'link' verb" \
    '{"tool_name":"mcp__plugin_atlassian_atlassian__createIssueLink","tool_input":{}}' \
    'jira/dist/index.js link'

# --- Allowed Atlassian tools (no verb in the map → no plugin equivalent) ---
for tool in lookupJiraAccountId getJiraIssueTypeMetaWithFields \
            getJiraProjectIssueTypesMetadata getIssueLinkTypes \
            addWorklogToJiraIssue atlassianUserInfo \
            getAccessibleAtlassianResources fetch search \
            getJiraIssueRemoteIssueLinks \
            getConfluencePage createConfluencePage updateConfluencePage \
            getConfluenceSpaces searchConfluenceUsingCql; do
    rc=$(run_case "{\"tool_name\":\"mcp__plugin_atlassian_atlassian__${tool}\",\"tool_input\":{}}")
    assert_rc "allow $tool" 0 "$rc"
done

# --- Fail OPEN on introspection failure ---
# CLI errors (non-zero exit) → must NOT block a mapped method.
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' "$STUB_ERR")
assert_rc "fail-open: introspection error allows getJiraIssue" 0 "$rc"
# CLI emits empty output → must NOT block.
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' "$STUB_EMPTY")
assert_rc "fail-open: empty introspection allows getJiraIssue" 0 "$rc"
# CLI file missing entirely → must NOT block.
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' "$TMPDIR_TEST/does-not-exist.js")
assert_rc "fail-open: missing CLI file allows getJiraIssue" 0 "$rc"

# --- Non-Atlassian MCP tools — pass through (never even introspect) ---
for tool in mcp__obsidian-vault__obsidian_get_file_contents \
            mcp__plugin_qmd_qmd__query \
            mcp__plugin_context7_context7__query-docs \
            mcp__plugin_playwright_playwright__browser_click; do
    rc=$(run_case "{\"tool_name\":\"${tool}\",\"tool_input\":{}}")
    assert_rc "passthrough $tool" 0 "$rc"
done

# --- Non-MCP tools (Bash, Edit, Read, etc.) — pass through ---
for tool in Bash Edit Write Read Grep PowerShell; do
    rc=$(run_case "{\"tool_name\":\"${tool}\",\"tool_input\":{}}")
    assert_rc "passthrough $tool" 0 "$rc"
done

# --- Bypass env var (honoured before introspection) ---
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' "$STUB_FULL" 'MCP_JIRA_OK=1')
assert_rc "bypass MCP_JIRA_OK=1" 0 "$rc"

# Bypass must produce ZERO stderr — operator should not see a misleading
# "considered blocking" message when the call will actually succeed.
stderr_bytes=$(printf '%s' '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue","tool_input":{}}' | env "JIRA_CLI=$STUB_FULL" MCP_JIRA_OK=1 bash "$HOOK" 2>&1 >/dev/null | wc -c)
assert_rc "bypass silent stderr" 0 "$stderr_bytes"

# --- Edge cases ---
# Missing tool_name → allow silently
rc=$(run_case '{"tool_input":{}}')
assert_rc "missing tool_name" 0 "$rc"

# Empty input → allow silently
rc=$(run_case '')
assert_rc "empty input" 0 "$rc"

# Garbage JSON → BLOCK (fail-closed; jq parse error on an Atlassian MCP
# call routed here by the matcher should refuse rather than silently
# allow a malformed/adversarial input through). This stays fail-CLOSED
# even though CLI introspection is fail-open.
rc=$(run_case 'not json at all')
assert_rc "garbage JSON fail-closed" 2 "$rc"

# tool_name with trailing CR → BLOCK (whitespace strip prevents the
# exact-match lookup from being bypassed by an attacker-controlled name
# like "...getJiraIssue\r").
rc=$(run_case "$(printf '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue\\r","tool_input":{}}')")
assert_rc "trailing CR in tool_name still blocks" 2 "$rc"

# tool_name with trailing space → BLOCK
rc=$(run_case '{"tool_name":"mcp__plugin_atlassian_atlassian__getJiraIssue ","tool_input":{}}')
assert_rc "trailing space in tool_name still blocks" 2 "$rc"

# tool_name as a non-string (number) → ALLOW (select(type=="string")
# rejects, then empty-string guard exits 0). The matcher should prevent
# this case in practice, but verify defense-in-depth.
rc=$(run_case '{"tool_name":42,"tool_input":{}}')
assert_rc "non-string tool_name allows" 0 "$rc"

if [ "$FAILED" -gt 0 ]; then
    echo "---"
    echo "FAIL $FAILED case(s)"
    exit 1
fi
echo "---"
echo "PASS all cases"
exit 0
